---
volumes:
  - mount_point: "{{ slurm_local_scratch_dir }}"
    device: '/dev/vdb'
    mounted_owner: root
    mounted_group: root
    mounted_mode: '0755'
    mount_options: >-
      rw,relatime
      {%- if ansible_facts['os_family'] == 'RedHat' and
             ansible_facts['distribution_major_version'] >= '8' -%}
        ,nofail,x-systemd.device-timeout=10
      {%- endif -%}
    type: ext4
...
