---
firewall_allowed_tcp_ports:
  - 22   # SSH.
  - 443  # SSH.
ssh_host_signer_hostnames: "{{ ansible_hostname }}\
  {% for network_id in ip_addresses[ansible_hostname] %}\
    {% if ip_addresses[ansible_hostname][network_id]['fqdn'] is defined and
          ip_addresses[ansible_hostname][network_id]['fqdn'] | length >= 1 %}\
      {% if ip_addresses[ansible_hostname][network_id]['fqdn'] == 'NXDOMAIN' %}\
        ,{{ ip_addresses[ansible_hostname][network_id]['address'] }}\
      {% else %}\
        ,{{ ip_addresses[ansible_hostname][network_id]['fqdn'] }}\
      {% endif %}\
    {% endif %}\
  {% endfor %}\
  {% for host in groups['jumphost'] %}\
    ,{{ host }}+{{ ansible_hostname }}\
  {% endfor %}"
volumes:
  - mount_point: '/groups'
    device: '/dev/vdb'
    mounted_owner: root
    mounted_group: root
    mounted_mode: '0755'
    mount_options: 'rw,relatime'
    type: ext4
...
