---
volumes:
  - mount_point: '/apps'
    device: '/dev/vdb'
    mounted_owner: root
    mounted_group: "{{ envsync_group }}"
    mounted_mode: '2755'
    mount_options: 'rw,relatime'
    type: ext4
...