---
volumes:
  - mount_point: "{{ hpc_env_prefix }}"
    device: '/dev/vdb'
    mounted_owner: root
    mounted_group: "{{ envsync_group }}"
    mounted_mode: '2775'
    mount_options: "rw,relatime{% if ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] >= '8' %},nofail,x-systemd.device-timeout=10{% endif %}"
    type: ext4
...
