firewall_allowed_tcp_ports:
  - "22"                  # SSH.
  - "{{ rsyslog_port | default('41514') }}"  # defined in inventory

# If possible (higly recommended) define this variables in the group variables,
# since both playbooks 'rsyslog_server' and 'rsyslog_client' are both using it
rsyslog_remote_path_key_dir: "/etc/pki/tls/private/"
rsyslog_remote_path_cert_dir: "/etc/pki/tls/certs/"
rsyslog_ca_key_file: "logs_{{ logs_ca_name }}.key" # must be encrypted
rsyslog_ca_cert_file: "logs_{{ logs_ca_name }}.pem"
rsyslog_repository_dir: "{{ playbook_dir }}/files/{{ stack_name }}/"
