---
- name: Configure azure general settings
  hosts: all
  connection: local
  gather_facts: false
  vars:
    #
    # Disable Ansible's interpretor detection logic,
    # which would fail to use the interpretor from an activated virtual environment.
    #
    ansible_python_interpreter: python
  roles:
    - azure_general
...
