---
- name: Install ldap_server role.
  hosts: ldap_server
  tasks:
  roles:
    - role: ldap_server
      when:
        - use_ldap | default(true, true) | bool
        - ldap_domains | default([]) | dict2items
          | selectattr('value.create_ldap', 'defined') | selectattr('value.create_ldap') | length >= 1
...
