---
- name: Deploy ssh (client) role on jumphosts.
  hosts:
    - jumphost
  roles:
    - ssh

- name: Deploy ssh (client) role on machines behind jumphosts.
  hosts:
    - build_server
    - cluster
    - chaperone
    - data_transfer
    - docs
    - irods
    - jenkins
    - repo
  roles:
    - ssh
...
