#installing the iRODS ICAT
- name: Installing the iRODS Package(s)
  become: true
  yum: 
    name: "{{ item }}"
    state: present
  loop:
  - irods-server
  - irods-database-plugin-postgres

- name: create_unattended_installation_json
  become: True
  template:
    src: unattended_install.json.j2
    dest: /root/unattended_install.json
  register: create_unattended_installation_json

- name: run_irods_installation_script
  become: True
  shell:  python /var/lib/irods/scripts/setup_irods.py --json_configuration_file=/root/unattended_install.json
  when: create_unattended_installation_json.changed
  async: 120
  poll: 1  
