---
- name: Install and configure local PostgreSQL hosting service
  include: pgsql_local.yml
  when: pgsql_server == "local"

- name: Configure remote PostgreSQL server access
  include: pgsql_remote.yml
  when: pgsql_server == "remote"

- name: Install and configure iCAT server
  include: icat.yml
...
