---
- name: Installing postgresql-server
  become: true
  ansible.builtin.yum:
    name: postgresql-server
    state: latest

- name: Installing python-psycopg2
  become: true
  ansible.builtin.yum:
    name: python-psycopg2
    state: latest

- name: Initializing PGSQL database
  become: true
  ansible.builtin.command: "/usr/bin/postgresql-setup initdb"
  args:
    creates: /var/lib/pgsql/data/pg_hba.conf

- name: Fixing pg_hba.conf to permit ipv4localhost password authentication
  ansible.builtin.lineinfile:
    name: /var/lib/pgsql/data/pg_hba.conf
    regexp: "host    all             all             127.0.0.1/32            ident"
    line: "host    all             all             127.0.0.1/32            md5"
    backrefs: true
  notify:
    - restart_postgresql
  become: true

- name: Fixing pg_hba.conf to permit ipv6 localhost password authentication
  ansible.builtin.lineinfile:
    name: /var/lib/pgsql/data/pg_hba.conf
    regexp: "host    all             all             ::1/128                 ident"
    line: "host    all             all             ::1/128                 md5"
    backrefs: true
  notify:
    - restart_postgresql
  become: true

- name: Enable postgresl service
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true
  become: true
...
