#
# This role may depend on the mount_volume role to mount the filesystems that must be exported over NFS.
#
---
- name: 'Install NFS utils.'
  yum:
    name: nfs-utils
  notify:
    - restart_nfs-server
    - export_nfs_shares
  become: true

- name: 'Enable and start nfs-server service.'
  systemd:
    name: nfs-server.service
    state: 'started'
    enabled: true
    daemon_reload: true
  notify:
    - export_nfs_shares
  become: true

- name: 'Add NFS share to /etc/exports.'
  lineinfile:
    path: /etc/exports
    line: "/mnt/{{ item.pfs }} {{ network_private_storage_cidr }}(rw,sync,root_squash,no_subtree_check)"
  with_items: "{{ pfs_mounts | selectattr('type', 'search', 'nfs') | selectattr('device', 'defined') | list }}"
  notify:
    - export_nfs_shares
  become: true

- name: Flush handlers
  meta: flush_handlers
...
