---
- name: Install service files.
  template:
    src: "templates/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0600
    owner: root
    group: root
  with_items:
      - openldap.service
      - phpldapadmin.service
  become: true

- name: Make directory for the openldap ldif volume.
  file:
    path: "/srv/openldap/custom"
    state: directory
    owner: root
    group: root
  become: true

- name: Install ldif files for overlays.
  copy:
    src: "files/{{ item }}"
    dest: "/srv/openldap/custom/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - 01-overlay-memberof
  become: true

- name: Make sure services are started.
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
      - openldap.service
      - phpldapadmin.service
  become: true
...
