---
ip_addresses:
  porch:
    wh_internal_management:
      address: 10.10.1.148
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    vlan16:
      address: 195.169.22.170
      netmask: /32
      fqdn: 'NXDOMAIN'
  wh-dai:
    wh_internal_management:
      address: 10.10.1.222
      netmask: /32
    wh_internal_storage:
      address: 10.10.2.218
      netmask: /32
  wh-repo:
    wh_internal_management:
      address: 10.10.1.153
      netmask: /32
  wh-sai:
    wh_internal_management:
      address: 10.10.1.71
      netmask: /32
    wh_internal_storage:
      address: 10.10.2.99
      netmask: /32
  wh-vcompute01:
    wh_internal_management:
      address: 10.10.1.65
      netmask: /32
    wh_internal_storage:
      address: 10.10.2.64
      netmask: /32
  wh-vcompute02:
    wh_internal_management:
      address: 10.10.1.110
      netmask: /32
    wh_internal_storage:
      address: 10.10.2.73
      netmask: /32
  wingedhelix:
    wh_internal_management:
      address: 10.10.1.229
      netmask: /32
    wh_internal_storage:
      address: 10.10.2.245
      netmask: /32
...
