---
slurm_cluster_name: 'wingedhelix'
slurm_cluster_domain: ''  # Only add hpc.rug.nl domain when jumphost is registered in DNS.
stack_name: "{{ slurm_cluster_name }}_cluster"  # stack_name must match the name of the folder that contains this vars.yml file.
stack_prefix: 'wh'
slurm_version: '20.11.8-1.el7.umcg'
slurm_partitions:
  - name: regular  # Must be in sync with group listed in Ansible inventory.
    default: yes
    nodes: "{{ stack_prefix }}-vcompute[01-02]"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: "{% if slurm_allow_jobs_to_span_nodes is defined and slurm_allow_jobs_to_span_nodes is true %}{{ groups['regular']|list|length }}{% else %}1{% endif %}"
    max_cores_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_cpus_per_node') | first }}"
    max_mem_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_mem_per_node') | first }}"
    local_disk: "{{ groups['regular'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['regular'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=0.5G" DenyQos=ds-short,ds-medium,ds-long'
  - name: user_interface  # Must be in sync with group listed in Ansible inventory.
    default: no
    nodes: "{{ slurm_cluster_name }}"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: 1
    max_cores_per_node: 1
    max_mem_per_node: 1024
    local_disk: "{{ groups['user_interface'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['user_interface'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=1.0G" AllowQos=ds-short,ds-medium,ds-long'
repo_manager: 'pulp'
mailhub: '192.168.0.5'     # we need to check or remove, as it looks like it is not used anywhere
rewrite_domain: "{{ stack_prefix }}-sai{% if slurm_cluster_domain | length %}.{{ slurm_cluster_domain }}{% endif %}"
figlet_font: 'ogre'
motd: |
      =========================================================
          Welcome to {{ slurm_cluster_name | capitalize }}
      =========================================================
additional_etc_hosts:
  - group: all
    hosts:
      - docs
      - docs_on_merlin
use_ldap: yes
create_ldap: no
ldap_uri: 'ldaps://svrs.id.rug.nl'
ldap_base: 'ou=gd,o=asds'
ldap_binddn: 'cn=clusteradminGD,o=asds'
ldap_group_object_class: 'groupofnames'
ldap_group_quota_soft_limit_template: 'ruggroupumcgquotaLFSsoft'
ldap_group_quota_hard_limit_template: 'ruggroupumcgquotaLFS'
cloud_image: CentOS 7
cloud_user: centos
network_public_external_id: vlan16
network_private_management_id: wh_internal_management
network_private_management_cidr: '10.10.1.0/24'
network_private_management_gw: '10.10.1.1'
network_private_storage_id: wh_internal_storage
network_private_storage_cidr: '10.10.2.0/24'
public_ip_addresses:
  porch: '195.169.22.170'
availability_zone: nova
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
  - 'docker'
local_admin_users:
  - 'egon'
  - 'ger'
  - 'gerben'
  - 'henkjan'
  - 'kim'
  - 'marieke'
  - 'marlies'
  - 'marloes'
  - 'morris'
  - 'pieter'
  - 'robin'
  - 'sandi'
  - 'wim'
data_transfer_only_group: 'umcg-sftp-only'
envsync_user: 'umcg-envsync'
envsync_group: 'umcg-depad'
functional_admin_group: 'umcg-funad'
hpc_env_prefix: '/apps'
regular_groups:
  - "{{ envsync_group }}"
  - "{{ functional_admin_group }}"
  - 'umcg-atd'

  - 'umcg-gap'
  - 'umcg-gd'
  - 'umcg-genomescan'
  - 'umcg-gsad'
  - 'umcg-gst'
  - 'umcg-vipt'
regular_users:
  - user: "{{ envsync_user }}"
    groups: ["{{ envsync_group }}"]
  - user: 'umcg-atd-ateambot'
    groups: ['umcg-atd']
    sudoers: '%umcg-atd'
  - user: 'umcg-gap-ateambot'
    groups: ['umcg-gap']
    sudoers: '%umcg-gap'
  - user: 'umcg-gd-ateambot'
    groups: ['umcg-gd']
    sudoers: '%umcg-gd'
  - user: 'umcg-genomescan-ateambot'
    groups: ['umcg-genomescan']
    sudoers: '%umcg-genomescan'
  - user: 'umcg-gsad-ateambot'
    groups: ['umcg-gsad']
    sudoers: '%umcg-gsad'
  - user: 'umcg-gst-ateambot'
    groups: ['umcg-gst']
    sudoers: '%umcg-gst'
#
# Shared storage related variables
#
pfs_mounts: [
  { pfs: 'umcgst12',
    device: '/dev/vdb',
    source: '10.10.2.20:/mnt',
    type: 'nfs4',    # checked with cat /proc/filesystem
    rw_options: 'defaults,_netdev,noatime,nodiratime,local_lock=flock',
    ro_options: 'defaults,_netdev,noatime,nodiratime,ro',
    machines: "{{ groups['sys_admin_interface'] }}" },
  { pfs: 'medgen_leucinezipper$',
    source: '//storage3.umcg.nl',
    type: 'cifs',    # checked with cat /proc/filesystem
    rw_options: 'vers=3.0,mfsymlinks,rw,soft,perm,dir_mode=02750,file_mode=0640',
    ro_options: 'vers=3.0,mfsymlinks,ro,soft,perm,dir_mode=02750,file_mode=0640',
    machines: "{{ groups['chaperone'] }}" },
#   { pfs: 'medgen_wingedhelix$',
#     source: '//storage3.umcg.nl',
#     type: 'cifs',    # checked with cat /proc/filesystem
#     rw_options: 'vers=3.0,mfsymlinks,rw,soft,perm,dir_mode=02750,file_mode=0640',
#     ro_options: 'vers=3.0,mfsymlinks,ro,soft,perm,dir_mode=02750,file_mode=0640',
#     machines: "{{ groups['chaperone'] }}" },

]
lfs_mounts: [
  { lfs: 'home',
    pfs: 'umcgst12',
    rw_machines: "{{ groups['cluster'] }}" },
  { lfs: 'tmp07',
    pfs: 'umcgst12',
    groups: ['umcg-atd', 'umcg-gap', 'umcg-gd', 'umcg-genomescan', 'umcg-gsad', 'umcg-gst', 'umcg-vipt'],
    rw_machines: "{{ groups['user_interface'] + groups['compute_vm'] }}" },
  { lfs: 'prm06',
    pfs: 'medgen_leucinezipper$',
    groups: ['umcg-atd', 'umcg-gap', 'umcg-gd', 'umcg-genomescan', 'umcg-gsad', 'umcg-gst', 'umcg-vipt'],
    rw_machines: "{{ groups['chaperone'] }}" },
  { lfs: 'dat06',
    pfs: 'medgen_leucinezipper$',
    groups: ['umcg-atd', 'umcg-gap', 'umcg-gd', 'umcg-genomescan', 'umcg-gsad', 'umcg-gst', 'umcg-vipt'],
    rw_machines: "{{ groups['chaperone'] }}" },
#   { lfs: 'prm07',
#     pfs: 'medgen_wingedhelix$',
#     groups: ['umcg-atd', 'umcg-gap', 'umcg-gd', 'umcg-genomescan', 'umcg-gsad', 'umcg-gst', 'umcg-vipt'],
#     rw_machines: "{{ groups['chaperone'] }}" },
#   { lfs: 'dat07',
#     pfs: 'medgen_wingedhelix$',
#     groups: ['umcg-atd', 'umcg-gap', 'umcg-gd', 'umcg-genomescan', 'umcg-gsad', 'umcg-gst', 'umcg-vipt'],
#     rw_machines: "{{ groups['chaperone'] }}" },
  { lfs: 'env07',
    pfs: 'umcgst12',
    ro_machines: "{{ groups['compute_vm'] + groups['user_interface'] }}",
    rw_machines: "{{ groups['deploy_admin_interface'] }}" },
]
...
