---
# Jumphosts security groups.
- name: "Create security groups for machines in 'jumphost' inventory group."
  when: "'jumphost' in inventory_groups_with_hosts_created_in_azure"
  block:
    - name: "Create security group {{ stack_prefix }}_jumphosts."
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ stack_prefix }}_jumphosts"
        purge_rules: true
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            source_address_prefix: '*'
            access: Allow
            priority: 101
          - name: SSH_fallback
            protocol: Tcp
            destination_port_range: 443
            source_address_prefix: '*'
            access: Allow
            priority: 102
          - name: ICMP
            protocol: Icmp
            source_address_prefix: '*'
            access: Deny
            priority: 103
- name: "Create security group {{ stack_prefix }}_cluster"
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ stack_prefix }}_cluster"
    purge_rules: true
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        source_address_prefix: "{{ network_cidr }}"
        access: Allow
        priority: 101
      - name: SSH_fallback
        protocol: Tcp
        destination_port_range: 443
        source_address_prefix: "{{ network_cidr }}"
        access: Allow
        priority: 102
      - name: ICMP
        protocol: Icmp
        source_address_prefix: "{{ network_cidr }}"
        access: Allow
        priority: 103
  vars:
    network_name: "{{ item }}"
    network_cidr: "{{ azure_networks | selectattr('name', 'equalto', item) | map(attribute='cidr') | first }}"
#    network_gateway: "{{ stack_networks | selectattr('name', 'equalto', item) | map(attribute='gateway') | first }}"
#    network_mtu_size: "{{ stack_networks | selectattr('name', 'equalto', item) | map(attribute='mtu_size') | first | default(omit) }}"
#    router_network: "{{ stack_networks | selectattr('name', 'equalto', item) | map(attribute='router_network') | first }}"
  with_items: "{{ azure_networks
                      | selectattr('type', 'equalto', 'management')
                      | selectattr('external', 'equalto', false)
                      | map(attribute='name') }}"
# TO-DO
## Data staging security groups.
#        - name: ssh
#          protocol: Tcp
#          destination_port_range: 22
#          source_address_prefix: '*'
#          priority: 101
#        - name: ssh_fallback
#          protocol: Tcp
#          destination_port_range: 443
#          source_address_prefix: '*'
#          priority: 102
#        - name: ICMP
#          protocol: Icmp
#          source_address_prefix: '*'
#          priority: 103
## (Pulp) repo server security group.
#        - protocol: tcp
#          port: 22  # SSH
#        - protocol: tcp
#          port: 443  # HTTPS
#        - protocol: icmp
#          port: -1  # ICMP protocol does not have any ports.
## Logs servers security group.
#        - protocol: tcp
#          port: 22  # SSH
#        - protocol: tcp
#          port: 443  # HTTPS
#        - protocol: tcp
#          port: 41514  # Rsyslog
#        - protocol: icmp
#          port: -1  # ICMP protocol does not have any ports.
...
