---
openstack_api_timeout: 240
stack_hosts_created_in_openstack: "{{ hostvars
    | json_query('* | [?cloud_flavor] | [].inventory_hostname')
    | flatten
    | unique }}"
openstack_computing_boot_from_volume: true
openstack_computing_terminate_volume: true
...
