---
#
# Allow passwordless sudo to functional accounts (e.g. for datamanager accounts) for indivual users or %groups.
# Who can become what can be specified in regular_users variable of group_vars/${clustername}/vars.yml.
#

- name: 'Find all ansible-managed files in /etc/sudoers.d/.'
  ansible.builtin.find:
    paths: '/etc/sudoers.d/'
    use_regex: true
    patterns: '.*ansible-managed.*'
  register: ansible_managed_sudoers
  become: true

- name: 'Remove outdated ansible-managed files from /etc/sudoers.d/.'
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ ansible_managed_sudoers.files | map(attribute='path') | list }}"
  when: item | regex_replace('.*ansible-managed-','') not in sudoers | default('') | selectattr('name', 'defined') | map(attribute='name') | list
  become: true

- name: 'Allow passwordless sudo to functional accounts.'
  ansible.builtin.template:
    src: 'templates/92-ansible-managed'
    dest: "/etc/sudoers.d/92-ansible-managed-{{ item.name }}"
    owner: 'root'
    group: 'root'
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
  with_items:
    - "{{ sudoers | selectattr('name', 'defined') }}"
  become: true
...
