---
- name: 'DEBUG: role got triggered.'
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ ldap_domains | default([])
                         | dict2items
                         | selectattr('value.create_ldap', 'defined')
                         | selectattr('value.create_ldap')
                         | list }}"

- name: Install OpenLDAP server.
  ansible.builtin.yum:
    state: latest
    update_cache: true
    name:
      - openldap-servers
  become: true

- name: Install key, certificate and dhparam files for TLS.
  ansible.builtin.copy:
    src: "files/{{ stack_name }}/{{ item.name }}"
    dest: "/etc/pki/tls/private/{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - name: ldap.key
      mode: '0600'
    - name: ldap.crt
      mode: '0644'
    - name: dhparam.pem
      mode: '0644'
  notify: restart_slapd
  become: true

# - name: Make directory for custom LDIF files.
#   ansible.builtin.file:
#     path: "/srv/openldap/custom"
#     state: directory
#     owner: root
#     group: root
#     mode: '0755'
#   become: true
# 
# - name: Install LDIF files for overlays.
#   ansible.builtin.copy:
#     src: "files/{{ item }}"
#     dest: "/srv/openldap/custom/{{ item }}"
#     owner: root
#     group: root
#     mode: '0644'
#   with_items:
#     - 01-overlay-memberof
#   notify:
#     - restart_openldap
#   become: true

- name: Make sure slapd.service (OpenLDAP server) is started.
  ansible.builtin.systemd:
    name: slapd.service
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: 
...
