---
slurm_cluster_name: 'fender'
slurm_cluster_domain: ''
stack_prefix: 'fd'
slurm_version: '20.11.8-1.el7.umcg'
repo_manager: 'pulp'
mailhub: '192.168.0.5'
rewrite_domain: "{{ stack_prefix }}-sai{% if slurm_cluster_domain | length %}.{{ slurm_cluster_domain }}{% endif %}"
figlet_font: 'slant'
motd: "To solve or not to solve, that's the question."
additional_etc_hosts:
  - group: all
    hosts:
      - docs
vcompute_hostnames: "{{ stack_prefix }}-vcompute[01-12]"
vcompute_sockets: 16
vcompute_cores_per_socket: 1
vcompute_real_memory: 64264
vcompute_max_cpus_per_node: "{{ vcompute_sockets * vcompute_cores_per_socket - 2 }}"
vcompute_max_mem_per_node: "{{ vcompute_real_memory - vcompute_sockets * vcompute_cores_per_socket * 512 }}"
vcompute_local_disk: 0      # [MB] the slurm setting, how it sees the disk local_volume_size_vcompute
vcompute_features: 'tmp10'
vcompute_ethernet_interfaces:
  - 'eth0'
  - 'eth1'
ui_hostnames: "{{ slurm_cluster_name }}"
ui_sockets: 4
ui_cores_per_socket: 1
ui_real_memory: 7820
ui_local_disk: 0
ui_features: 'prm10,tmp10'
ui_ethernet_interfaces:
  - 'eth0'
  - 'eth1'
ssh_host_signer_ca_private_key: "{{ ssh_host_signer_ca_keypair_dir }}/fender-ca"
use_ldap: yes
create_ldap: yes
ldap_uri: ldaps://fd-dai
ldap_base: dc=hpc,dc=rug,dc=nl
ldap_binddn: cn=admin,dc=hpc,dc=rug,dc=nl
ldap_domain: hpc.rug.nl
cloud_image: CentOS7-Cloud
cloud_user: centos
flavor_jumphost: 1c2m20d # s1.small
flavor_ui: 4c8m80d # s1.large
flavor_vcompute: 16c64m100d # s1.gargantuan
flavor_management: 4c4m60d
network_public_external_id: public
network_private_management_id: "{{ stack_prefix }}_internal_management"
network_private_management_cidr: '10.10.1.0/24'
network_private_management_gw: '10.10.1.1'
network_private_storage_id: "subnet-nfs-data-2541"
network_private_storage_cidr: '10.35.141.0/24'
public_ip_addresses:
  corridor: '45.88.81.213'
availability_zone: nova
local_volume_size_repo: 30
local_volume_size_vcompute: 1  # [GB] disk of /dev/vdb -> /local
local_volume_size_dai: 2000    # used for /apps
local_volume_size_sai: 1
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
  - 'docker'
local_admin_users:
  - 'egon'
  - 'gerben'
  - 'henkjan'
  - 'marieke'
  - 'marloes'
  - 'morris'
  - 'pieter'
  - 'sandi'
  - 'wim'
envsync_user: 'envsync'
envsync_group: 'depad'
functional_admin_group: 'funad'
hpc_env_prefix: '/apps'
regular_groups:
  - "{{ envsync_group }}"
  - "{{ functional_admin_group }}"
  - 'users'
  - 'solve-rd'
  - 'umcg-atd'
regular_users:
  - user: "{{ envsync_user }}"
    groups: ["{{ envsync_group }}"]
  - user: 'solve-rd-dm'
    groups: ['solve-rd']
    sudoers: '%solve-rd'
  - user: 'umcg-atd-dm'
    groups: ['umcg-atd']
    sudoers: '%umcg-atd'
  - user: 'solve-rd-ateambot'
    groups: ['solve-rd']
    sudoers: '%solve-rd'
  - user: 'gvdvries'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'mbijlsma'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'mswertz'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'pneerincx'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'rkanninga'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'ljohansson'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'ddanis'
    groups: ['users', 'solve-rd']
  - user: 'dhendriksen'
    groups: ['users', "{{ envsync_group }}", 'solve-rd']
  - user: 'ksablauskas'
    groups: ['users', 'solve-rd']
  - user: 'wsteyaert'
    groups: ['users', 'solve-rd']
  - user: 'slaurie'
    groups: ['users', 'solve-rd']
  - user: 'jvdvelde'
    groups: ['users', 'solve-rd']
  - user: 'fmusacchia'
    groups: ['users', 'solve-rd']
  - user: 'psivakumar'
    groups: ['users', 'solve-rd']
  - user: 'fandrade'
    groups: ['users', 'solve-rd']
  - user: 'gdemidov'
    groups: ['users', 'solve-rd']
  - user: 'amohan'
    groups: ['users', 'solve-rd']
  - user: 'cthomas'
    groups: ['users', 'solve-rd']
  - user: 'mbenjamins'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'lmatalonga'
    groups: ['users', 'solve-rd']
  - user: 'gbullich'
    groups: ['users', 'solve-rd']
  - user: 'ebenetti'
    groups: ['users', 'solve-rd']
  - user: 'kdelange'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'scimerman'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'sli'
    groups: ['users', 'solve-rd']
  - user: 'rschuele'
    groups: ['users', 'solve-rd']
  - user: 'jvandrovcova'
    groups: ['users', 'solve-rd']
  - user: 'itepaske'
    groups: ['users', 'solve-rd']
  - user: 'jpelaez'
    groups: ['users', 'solve-rd']
  - user: 'asommer'
    groups: ['users', 'solve-rd']
  - user: 'droelofs'
    groups: ['users', 'solve-rd']
  - user: 'dlagorce'
    groups: ['users', 'solve-rd']
  - user: 'gwarren'
    groups: ['users', 'solve-rd']
  - user: 'mmehtarizadeh'
    groups: ['users', 'solve-rd']
  - user: 'cveal'
    groups: ['users', 'solve-rd']
  - user: 'rthompson'
    groups: ['users', 'solve-rd']
  - user: 'alaner'
    groups: ['users', 'solve-rd']
  - user: 'edeboer01'
    groups: ['users', 'solve-rd']
  - user: 'adenommepichon'
    groups: ['users', 'solve-rd']
  - user: 'avitobello'
    groups: ['users', 'solve-rd']
  - user: 'yduffourd'
    groups: ['users', 'solve-rd']
  - user: 'elopez02'
    groups: ['users', 'solve-rd']
  - user: 'amarcegrau'
    groups: ['users', 'solve-rd']
  - user: 'cwilke'
    groups: ['users', 'solve-rd']
  - user: 'ajackson'
    groups: ['users', 'solve-rd']
  - user: 'byaldiz'
    groups: ['users', 'solve-rd']
  - user: 'bcharbon'
    groups: ['users', "{{ envsync_group }}", 'solve-rd']
  - user: 'amaver'
    groups: ['users', 'solve-rd']
  - user: 'cgilissen'
    groups: ['users', 'solve-rd']
  - user: 'arump'
    groups: ['users', 'solve-rd']
  - user: 'abuhrmann'
    groups: ['users', 'solve-rd']
  - user: 'mferreira'
    groups: ['users', 'solve-rd']
  - user: 'iparamonov'
    groups: ['users', 'solve-rd']
  - user: 'ohongnat'
    groups: ['users', 'solve-rd']
  - user: 'mslofstra'
    groups: ['users', 'solve-rd']
  - user: 'dwilliam'
    groups: ['users', 'solve-rd']
  - user: 'mbeukers'
    groups: ['users', 'solve-rd']
  - user: 'rsietsma'
    groups: ['users', 'solve-rd']
  - user: 'fgao'
    groups: ['users', 'solve-rd']
  - user: 'druvolo'
    groups: ['users', 'solve-rd']
  - user: 'ftranmauthem'
    groups: ['users', 'solve-rd']
#
# Shared storage related variables
#
pfs_mounts: [
  { pfs: 'ecst02',
    source: '10.35.141.251:/solve-rd-98599485/',
    type: 'nfs',
    rw_options: 'defaults,_netdev,noatime,nodiratime',
    ro_options: 'defaults,_netdev,noatime,nodiratime,ro' },
]
lfs_mounts: [
  { lfs: 'home',
    pfs: 'ecst02',
    machines: "{{ groups['cluster'] }}" },
  { lfs: 'tmp10',
    pfs: 'ecst02',
    groups: ['umcg-atd', 'solve-rd'] },
  { lfs: 'prm10',
    pfs: 'ecst02',
    groups: ['umcg-atd', 'solve-rd'] },
  { lfs: 'env10',
    pfs: 'ecst02',
    machines: "{{ groups['compute_vm'] + groups['user_interface'] }}" },
]
ega_fuse_client_mounts:
  solve_rd: '/groups/solve-rd/prm10/ega-fuse-client'
ega_fuse_client_java_home: '/etc/alternatives/jre_11_openjdk'
interfaces:
  - device: 'eth0'
    bootproto: 'dhcp'
  - device: 'eth1' 
    bootproto: 'dhcp'
...
