---
slurm_cluster_name: 'fender'
slurm_cluster_domain: ''
stack_name: "{{ slurm_cluster_name }}_cluster"  # stack_name must match the name of the folder that contains this vars.yml file.
stack_prefix: 'fd'
slurm_version: '20.11.8-1.el7.umcg'
slurm_partitions:
  - name: regular  # Must be in sync with group listed in Ansible inventory.
    default: yes
    nodes: "{{ stack_prefix }}-vcompute[01-12]"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: "{% if slurm_allow_jobs_to_span_nodes is defined and slurm_allow_jobs_to_span_nodes is true %}{{ groups['regular']|list|length }}{% else %}1{% endif %}"
    max_cores_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_cpus_per_node') | first }}"
    max_mem_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_mem_per_node') | first }}"
    local_disk: "{{ groups['regular'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['regular'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=0.5G" DenyQos=ds-short,ds-medium,ds-long'
  - name: user_interface  # Must be in sync with group listed in Ansible inventory.
    default: no
    nodes: "{{ slurm_cluster_name }}"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: 1
    max_cores_per_node: 1
    max_mem_per_node: 1024
    local_disk: "{{ groups['user_interface'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['user_interface'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=1.0G" AllowQos=ds-short,ds-medium,ds-long'
repo_manager: 'pulp'
mailhub: '192.168.0.5'
rewrite_domain: "{{ stack_prefix }}-sai{% if slurm_cluster_domain | length %}.{{ slurm_cluster_domain }}{% endif %}"
figlet_font: 'slant'
motd: "To solve or not to solve, that's the question."
additional_etc_hosts:
  - group: all
    hosts:
      - docs
      - docs_on_merlin
use_ldap: yes
create_ldap: yes
ldap_uri: ldaps://fd-dai
ldap_base: dc=hpc,dc=rug,dc=nl
ldap_binddn: cn=admin,dc=hpc,dc=rug,dc=nl
ldap_domain: hpc.rug.nl
cloud_image: CentOS7-Cloud
cloud_user: centos
network_public_external_id: public
network_private_management_id: "{{ stack_prefix }}_internal_management"
network_private_management_cidr: '10.10.1.0/24'
network_private_management_gw: '10.10.1.1'
network_private_storage_id: "subnet-nfs-data-2541"
network_private_storage_cidr: '10.35.141.0/24'
public_ip_addresses:
  corridor: '45.88.81.213'
availability_zone: nova
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
  - 'docker'
local_admin_users:
  - 'egon'
  - 'gerben'
  - 'henkjan'
  - 'marieke'
  - 'marloes'
  - 'morris'
  - 'pieter'
  - 'sandi'
  - 'wim'
envsync_user: 'envsync'
envsync_group: 'depad'
functional_admin_group: 'funad'
hpc_env_prefix: '/apps'
regular_groups:
  - "{{ envsync_group }}"
  - "{{ functional_admin_group }}"
  - 'users'
  - 'solve-rd'
  - 'umcg-atd'
regular_users:
  - user: "{{ envsync_user }}"
    groups: ["{{ envsync_group }}"]
  - user: 'solve-rd-dm'
    groups: ['solve-rd']
    sudoers: '%solve-rd'
  - user: 'umcg-atd-dm'
    groups: ['umcg-atd']
    sudoers: '%umcg-atd'
  - user: 'solve-rd-ateambot'
    groups: ['solve-rd']
    sudoers: '%solve-rd'
  - user: 'gvdvries'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'mbijlsma'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'mswertz'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'pneerincx'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'rkanninga'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'ljohansson'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'ddanis'
    groups: ['users', 'solve-rd']
  - user: 'dhendriksen'
    groups: ['users', "{{ envsync_group }}", 'solve-rd']
  - user: 'ksablauskas'
    groups: ['users', 'solve-rd']
  - user: 'wsteyaert'
    groups: ['users', 'solve-rd']
  - user: 'slaurie'
    groups: ['users', 'solve-rd']
  - user: 'jvdvelde'
    groups: ['users', 'solve-rd']
  - user: 'fmusacchia'
    groups: ['users', 'solve-rd']
  - user: 'psivakumar'
    groups: ['users', 'solve-rd']
  - user: 'fandrade'
    groups: ['users', 'solve-rd']
  - user: 'gdemidov'
    groups: ['users', 'solve-rd']
  - user: 'amohan'
    groups: ['users', 'solve-rd']
  - user: 'cthomas'
    groups: ['users', 'solve-rd']
  - user: 'mbenjamins'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'lmatalonga'
    groups: ['users', 'solve-rd']
  - user: 'gbullich'
    groups: ['users', 'solve-rd']
  - user: 'ebenetti'
    groups: ['users', 'solve-rd']
  - user: 'kdelange'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'scimerman'
    groups: ['users', "{{ envsync_group }}", 'umcg-atd', 'solve-rd']
  - user: 'sli'
    groups: ['users', 'solve-rd']
  - user: 'rschuele'
    groups: ['users', 'solve-rd']
  - user: 'jvandrovcova'
    groups: ['users', 'solve-rd']
  - user: 'itepaske'
    groups: ['users', 'solve-rd']
  - user: 'jpelaez'
    groups: ['users', 'solve-rd']
  - user: 'asommer'
    groups: ['users', 'solve-rd']
  - user: 'droelofs'
    groups: ['users', 'solve-rd']
  - user: 'dlagorce'
    groups: ['users', 'solve-rd']
  - user: 'gwarren'
    groups: ['users', 'solve-rd']
  - user: 'mmehtarizadeh'
    groups: ['users', 'solve-rd']
  - user: 'cveal'
    groups: ['users', 'solve-rd']
  - user: 'rthompson'
    groups: ['users', 'solve-rd']
  - user: 'alaner'
    groups: ['users', 'solve-rd']
  - user: 'edeboer01'
    groups: ['users', 'solve-rd']
  - user: 'adenommepichon'
    groups: ['users', 'solve-rd']
  - user: 'avitobello'
    groups: ['users', 'solve-rd']
  - user: 'yduffourd'
    groups: ['users', 'solve-rd']
  - user: 'elopez02'
    groups: ['users', 'solve-rd']
  - user: 'amarcegrau'
    groups: ['users', 'solve-rd']
  - user: 'cwilke'
    groups: ['users', 'solve-rd']
  - user: 'ajackson'
    groups: ['users', 'solve-rd']
  - user: 'byaldiz'
    groups: ['users', 'solve-rd']
  - user: 'bcharbon'
    groups: ['users', "{{ envsync_group }}", 'solve-rd']
  - user: 'amaver'
    groups: ['users', 'solve-rd']
  - user: 'cgilissen'
    groups: ['users', 'solve-rd']
  - user: 'arump'
    groups: ['users', 'solve-rd']
  - user: 'abuhrmann'
    groups: ['users', 'solve-rd']
  - user: 'mferreira'
    groups: ['users', 'solve-rd']
  - user: 'iparamonov'
    groups: ['users', 'solve-rd']
  - user: 'ohongnat'
    groups: ['users', 'solve-rd']
  - user: 'mslofstra'
    groups: ['users', 'solve-rd']
  - user: 'dwilliam'
    groups: ['users', 'solve-rd']
  - user: 'mbeukers'
    groups: ['users', 'solve-rd']
  - user: 'rsietsma'
    groups: ['users', 'solve-rd']
  - user: 'fgao'
    groups: ['users', 'solve-rd']
  - user: 'druvolo'
    groups: ['users', 'solve-rd']
  - user: 'ftranmauthem'
    groups: ['users', 'solve-rd']
  - user: 'mjohari'
    groups: ['users', 'solve-rd']
  - user: 'mchahdil'
    groups: ['users', 'solve-rd']
  - user: 'aesteve'
    groups: ['users', 'solve-rd']
  - user: 'cdoornbos'
    groups: ['users', 'solve-rd']
#
# Shared storage related variables
#
pfs_mounts: [
  { pfs: 'ecst02',
    source: '10.35.141.251:/solve-rd-98599485/',
    type: 'nfs',
    rw_options: 'defaults,_netdev,noatime,nodiratime',
    ro_options: 'defaults,_netdev,noatime,nodiratime,ro',
    machines: "{{ groups['sys_admin_interface'] }}" },
]
lfs_mounts: [
  { lfs: 'home',
    pfs: 'ecst02',
    rw_machines: "{{ groups['cluster'] }}" },
  { lfs: 'tmp10',
    pfs: 'ecst02',
    groups: ['umcg-atd', 'solve-rd'],
    rw_machines: "{{ groups['user_interface'] + groups['compute_vm'] }}" },
  { lfs: 'prm10',
    pfs: 'ecst02',
    groups: ['umcg-atd', 'solve-rd'],
    rw_machines: "{{ groups['user_interface'] }}" },
  { lfs: 'env10',
    pfs: 'ecst02',
    ro_machines: "{{ groups['compute_vm'] + groups['user_interface'] }}",
    rw_machines: "{{ groups['deploy_admin_interface'] }}" },
]
ega_fuse_client_mounts:
  solve_rd: '/groups/solve-rd/prm10/ega-fuse-client'
ega_fuse_client_java_home: '/etc/alternatives/jre_11_openjdk'
interfaces:
  - device: 'eth0'
    bootproto: 'dhcp'
  - device: 'eth1' 
    bootproto: 'dhcp'
...
