#
# See README.md for instructins how to use this playbook.
#
---
#
# Dummy play to ping jumphosts and establish a persisting SSH connection
# before trying to connect to the machines behind the jumphost,
# which may otherwise fail when SSH connection multiplexing is used.
#
- name: 'Dummy play to ping jumphosts and establish a persistent SSH connection.'
  hosts: jumphost

- import_playbook: single_group_playbooks/pre_deploy_checks.yml

- import_playbook: single_group_playbooks/jumphost.yml

- import_playbook: single_group_playbooks/repo.yml

- import_playbook: single_group_playbooks/cluster_part1.yml

- import_playbook: single_group_playbooks/ldap_server.yml

- import_playbook: single_group_playbooks/nfs_server.yml

- import_playbook: single_group_playbooks/cluster_part2.yml

- import_playbook: single_group_playbooks/sys_admin_interface.yml

- import_playbook: single_group_playbooks/deploy_admin_interface.yml

- import_playbook: single_group_playbooks/user_interface.yml

- import_playbook: single_group_playbooks/compute_vm.yml

- import_playbook: single_group_playbooks/docs.yml

- import_playbook: single_group_playbooks/rsyslog.yml
...
