#
# Install roles and collections from the default Ansible Galaxy server.
#
---
roles:
  - src: geerlingguy.repo-epel
    version: 3.0.0
  - src: geerlingguy.security
    version: 2.0.1
  - src: geerlingguy.postgresql
    version: 3.1.1
collections:
  - name: ansible.utils
    version: '>=2.0.1'
  - name: ansible.posix
    version: '>=1.2.0'
  - name: community.general
    version: '>=3.0.2'
  - name: community.mysql
    version: '>=2.3.5'
  - name: openstack.cloud
    version: '>=1.5.0,<2.0.0'
  - name: pulp.pulp_installer
    version: '==3.17.2'
  - name: pulp.squeezer
    version: '>=0.0.11'
...
