---
#
# Important: maintain correct handler order.
# Handlers are executed in the order in which they are defined
# and not in the order in which they are listed in a "notify: handler_name" statement!
#
- name: Running update-ca-trust when certificates have changed.
  ansible.builtin.command:
    cmd: update-ca-trust extract
  become: true
  listen: update-ca-trust

- name: Restart nslcd service.
  ansible.builtin.service:
    name: nslcd
    state: restarted
  become: true
  listen: restart_nslcd

- name: Restart sshd service.
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true
  listen: restart_sshd

- name: Run authconfig update to enable ldap.
  ansible.builtin.command: "authconfig --enableldap --enableldapauth --update"
  become: true
  listen: authconfig_enable_ldap
...
