---
- name: Update system-wide crypto policies
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/roles/sshd/handlers/update-crypto-policies.yml"
  listen: update-crypto-policies

- name: Restart sshd service.
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true
  listen: restart_sshd
...
