---
- name: Find all subpolicy files.
  ansible.builtin.find:
    paths:
      - /etc/crypto-policies/policies/modules/
    patterns: '*.pmod'
  register: sshd_found_crypto_subpolicy_files

- name: Update system-wide crypto policies.
  ansible.builtin.shell:
    cmd: |
         active_policy="$(update-crypto-policies --show)"
         update-crypto-policies --set "${active_policy%%:*}:{{ sshd_available_crypto_subpolicies | join(':') }}"
  changed_when: true
  vars:
    sshd_available_crypto_subpolicies: "{{ sshd_found_crypto_subpolicy_files.files
        | map(attribute='path') | map('basename') | map('splitext') | map('first')
        | unique | list }}"
  become: true
...
