---
- name: Find all subpolicy files.
  ansible.builtin.find:
    paths:
      - /etc/crypto-policies/policies/modules/
    patterns: '*.pmod'
  register: sshd_found_crypto_subpolicy_files

- name: Update system-wide crypto policies.
  ansible.builtin.shell:
    cmd: |
         active_policy="$(update-crypto-policies --show)"
         update-crypto-policies --set "${active_policy%%:*}:{{ sshd_available_crypto_subpolicies_formatted }}"
  register: sshd_update_crypto_policies
  changed_when:
    - 'sshd_update_crypto_policies.rc == 0'
    - '"Setting system policy to" in sshd_update_crypto_policies.stdout'
    - 'sshd_available_crypto_subpolicies_formatted in sshd_update_crypto_policies.stdout'
  vars:
    sshd_available_crypto_subpolicies: "{{ sshd_found_crypto_subpolicy_files.files
        | map(attribute='path') | map('basename') | map('splitext') | map('first')
        | unique | list }}"
    sshd_available_crypto_subpolicies_formatted: "{{ sshd_available_crypto_subpolicies | join(':') | replace('.pmod','') }}"
  become: true
...
