---
- name: Install rsyslog on centos
  ansible.builtin.yum: name=rsyslog state=latest update_cache=yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  become: true

- name: Install rsyslog on ubuntu
  apt: name=rsyslog state=latest update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true

- name: configure rsyslog server.
  ansible.builtin.lineinfile:
    dest: /etc/rsyslog.conf
    line: "*.* @{{ item }}:514"
  with_items: "{{ rsyslog_remote_servers }}"
  become: true

- name: restart rsyslog
  ansible.builtin.systemd: name=rsyslog state=restarted
  become: true
...