---
- name: Enable swap.
  ansible.builtin.include_tasks:
    file: enable_swap.yml
  when: swap_file_state == 'enabled'

- name: Disable swap.
  ansible.builtin.include_tasks:
    file: disable_swap.yml
  when: swap_file_state != 'enabled'
...
