---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: '###==-> Roles for build library. <-==###'
  hosts:
    - build_servers
  roles:
    - admin_users
    - ssh_host_signer
    - iptables
    - yum_repos
    - logrotate
    - remove
    - update
    - sshd
    - basic_security
    - regular_users
    - cluster       # installing software
    - sudoers
...
