---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: '###==-> Roles for chaperones. <-==###'
  hosts:
    - chaperone
  roles:
    - locale
    - ssh
    - cluster
    - regular_users
    - shared_storage
    - logs_toprm
    - sudoers
    - build_environment
    - envsync
...
