---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: '###==-> Roles for chaperones. <-==###'
  hosts:
    - chaperone
  connection: local
  roles:
    - regular_users
    - shared_storage
    - sudoers
    - envsync
...
