---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: '###==-> Basic roles for all cluster machines part 1. <-==###'
  hosts:
    - cluster
  roles:
    - admin_users
    - ssh_host_signer
    - iptables
    - ssh_known_hosts
    - swap
    - {role: pulp_client, when: repo_manager == 'pulp'}
    - {role: yum_repos, when: repo_manager == 'none'}
    - {role: yum_local, when: local_yum_repository is defined}
    - static_hostname_lookup
    - logrotate
    - remove
    - update
    - logins
    - figlet_motd
    - node_exporter
    - cluster
    - {role: logs_client, when: stacks_logs_servers is defined}
    - gpu            # needs to run after role 'cluster'
    - resolver
    - coredumps
...
