#
# This play depends on:
#   * cluster_part1.yml
#   * cluster_part2.yml
#
---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: '###==-> Extra roles for compute nodes. <-==###'
  hosts:
    - compute_vm
  roles:
    - mount_volume
    - slurm
...
