---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: Import initialization playbook for all hosts.
  ansible.builtin.import_playbook: init.yml

- name: '###==-> Roles for data transfer servers. <-==###'
  hosts:
    - data_transfer
  roles:
    - iptables
    - grub
    - locale
    - logrotate
    - remove
    - update
    - logins
    - role: sssd
      when: use_sssd | default(false) | bool
    - sshd
    - basic_security
    - rsyncd
    - regular_users
    - mount_volume
...
