---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: '###==-> Roles for data transfer servers. <-==###'
  hosts:
    - data_transfer
  roles:
    - admin_users
    - ssh_host_signer
    - iptables
    - logrotate
    - remove
    - update
    - epel
    - logins
    - role: ldap
      when:
        - use_ldap | default(true) | bool
        - not use_sssd | default(false) | bool
    - role: sssd
      when:
        - use_ldap | default(true) | bool
        - use_sssd | default(false) | bool
    - sshd
    - basic_security
    - rsyncd
    - regular_users
    - mount_volume
...
