---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: '###==-> Roles for documentation servers. <-==###'
  hosts:
    - docs
  roles:
    - admin_users
    - ssh_host_signer
    - iptables
    - grub
    - yum_repos
    - locale
    - logrotate
    - remove
    - update
    - sshd
    - basic_security
    - online_docs
...
