---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: 'Satisfy dependencies and install iCAT'
  hosts: irods
  roles:
    - static_hostname_lookup
    - admin_users
    - ssh_host_signer
    - iptables
    - ssh  # client
    - grub
    - pulp_client
    - locale
    - logrotate
    - logins
    - sshd
    - basic_security
    - remove
    - update
    - docker
    - irods
    - irods_davrods
...
