---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: '###==-> Roles for jumphosts. <-==###'
  hosts:
    - jumphost
  roles:
    - admin_users
    - ssh_host_signer
    - iptables
    - ssh_known_hosts
    - {role: yum_local, when: local_yum_repository is defined}
    - {role: yum_repos, when: repo_manager == 'none'}
    - locale
    - logrotate
    - remove
    - update
    - logins
    - role: ldap
      when:
        - use_ldap | default(true) | bool
        - not use_sssd | default(false) | bool
    - role: sssd
      when:
        - use_ldap | default(true) | bool
        - use_sssd | default(false) | bool
    - sshd
    - static_hostname_lookup
    - basic_security
    - {role: logs_client, when: stacks_logs_servers is defined}
    - regular_users
    # Disabled monitoring: needs update. See also:
    # https://github.com/rug-cit-hpc/league-of-robots/issues/294
    # - node_exporter
    # - {role: grafana_proxy, when: ansible_hostname == 'airlock'}
...
