#
# This play depends on:
#   * cluster_part1.yml
#
---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: '###==-> Extra roles for LDAP account server. <-==###'
  hosts:
    - ldap_server
  roles:
    - role: ldap_server
      when:
        - use_ldap | default(true, true) | bool
        - ldap_domains | default([]) | dict2items
          | selectattr('value.create_ldap', 'defined') | selectattr('value.create_ldap') | length >= 1
...
