---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: Configure syslog > servers <
  roles:
    - admin_users
    - ssh_host_signer
    - iptables
    - update
    - iptables
    - ssh_known_hosts
    - {role: yum_local, when: local_yum_repository is defined}
    - logrotate
    - {role: geerlingguy.repo-epel, become: true}
    - sshd
    - {role: geerlingguy.security, become: true}
    - logs_server
  hosts: logs

- name: Configure syslog > clients <
  roles:
    - role: logs_client
#      when: (syslog_external_servers is defined and ( syslog_external_servers|length>0 )) or
#            ( stacks_logs_servers is defined and ( stacks_logs_servers|length>0 ) )
  hosts:
    - jumphost
    - cluster
    - repo
    - syslog
    - chaperone
...
