---
- import_playbook: pre_deploy_checks.yml

- name: Configure rsyslog servers
  hosts: rsyslog
  roles:
    - role: rsyslog_server
      when: groups['rsyslog'] is defined and ( groups['rsyslog']|length>0 )

- name: Configure rsyslog clients
  hosts:
    - jumphost
    - cluster
    - repo
    - rsyslog
  roles:
    - role: rsyslog_client
      when: (rsyslog_external_servers is defined and ( rsyslog_external_servers|length>0 )) or
            ( groups['rsyslog'] is defined and ( groups['rsyslog']|length>0 ) )
...
