---
- name: Install EGA Fuse client.
  yum:
    state: latest
    name:
      - ega-fuse-client
  become: true
  notify: restart_fuser-layer

- name: Create /usr/local/fuse-layer directory.
  file:
    path: /usr/local/fuse-layer
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true
  notify: restart_fuser-layer

- name: Install service files.
  template:
    src: templates/ega-fuse-client.service
    dest: /etc/systemd/system/ega-fuse-client.service
    mode: '0644'
    owner: root
    group: root
  tags:
      - service-files
  become: true
  notify: restart_fuser-layer

- name: Install config.ini files.
  template:
    src: templates/config.ini
    dest: /usr/local/fuse-layer/config.ini
    mode: '0644'
    owner: root
    group: root
  become: true
  notify: restart_fuser-layer

- name: Make sure fuse-layer service is enabled and started.
  systemd:
    name: 'ega-fuse-client.service'
    state: 'started'
    enabled: 'yes'
    daemon_reload: yes
  become: true
  notify: restart_fuser-layer
