---
- name: Check if firewalld package is installed on RedHat.
  ansible.builtin.shell: yum list installed firewalld
  args:
    warn: no
  register: firewalld_installed
  ignore_errors: true
  changed_when: false
  when: ansible_os_family == "RedHat" and iptables_disable_firewalld

- name: Disable the firewalld service on RedHat.
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
    daemon_reload: true
  when: ansible_os_family == "RedHat" and iptables_disable_firewalld and firewalld_installed.rc == 0
  become: true
...