---
- name: List installed packages.
  ansible.builtin.yum:
    list: installed
  register: yum_list_installed
  changed_when: false

- name: Disable the firewalld service if the firewalld package was installed.
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
    daemon_reload: true
  when: yum_list_installed.results | selectattr('name', 'equalto', 'firewalld') | list | length > 0
  become: true
...
