---
- name: Check if firewalld package is installed on RedHat.
  ansible.builtin.command:
    cmd: yum list installed firewalld
  register: firewalld_installed
  failed_when:
    - firewalld_installed.rc != 0
    - ('No matching Packages to list' not in firewalld_installed.stderr)
  changed_when: false
  when: ansible_os_family == "RedHat" and iptables_disable_firewalld

- name: Disable the firewalld service on RedHat.
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
    daemon_reload: true
  when: ansible_os_family == "RedHat" and iptables_disable_firewalld and firewalld_installed.rc == 0
  become: true
...
