---
- name: (Re)build and start davrods docker instance ...
  ansible.builtin.command:
    chdir: '{{ davrods_user_home_path }}/{{ davrods_docker_folder }}'
    cmd: docker-compose up -d --build --force-recreate
  register: result
  failed_when:
    - result.rc != 0
  changed_when: false
  become_user: '{{ davrods_docker_user }}'
  become: true
  listen: davrods_build_up

...
