---
- name: template network devices' files
  ansible.builtin.template:
    src: "interface_template.j2"
    dest: "/etc/sysconfig/network-scripts/{{network_device_file_prefix}}{{ item.device }}"
    mode: 0644
  become: true  
  with_items: "{{ interfaces }}"
  when: interfaces is defined
  register: changed_devices
  notify: restart_ifaces

- name: enable service at boot
  ansible.builtin.systemd:
    name: network.service
    enabled: yes
    state: started
  become: true
