---
# Gathering logs server list                                                    
- name: Include static inventory logs_library.yml                               
  ansible.builtin.include_vars:                                                 
    file: "{{ inventory_dir }}/logs_library.yml"                                
    name: "logs_servers_library"                                                
  register: logs_server_library                                                 
  delegate_to: localhost                                                        
  connection: local                                                             
  run_once: true                                                                
  tags:                                                                         
    - test

#- name: Compile the list of logs server names
#  ansible.builtin.set_fact:
#    rsyslogs_ext_ips: "{{ rsyslogs_ext_ips | default([]) + [item['name']] }}"
#  loop: "{{ logs_servers }}"
#  when: logs_servers is defined and logs_servers|length>0
#  register: rsys_ext_ips
#  delegate_to: 127.0.0.1
#  connection: local
#  run_once: true
#  tags:
#    - test
#
- name: Collect IP addresses of logs_library
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/group_vars/logs_library/ip_addresses.yml"
    name: "logs_ips"
  delegate_to: localhost
  connection: local
  run_once: true
  tags:
    - test

- name: Compile the list of logs external IP addresses
  ansible.builtin.set_fact:
    rsyslogs_ext_ips: "{{ rsyslogs_ext_ips | default([]) + [ logs_ips.ip_addresses[item['name']][item['external_network']].address ] }}"
  loop: "{{ logs_servers }}"
  register: rsys_ext_ips
  delegate_to: 127.0.0.1
  connection: local
  run_once: true

- name: 'Get {{ logs_toprm_chaperone_user }} home directory'
  ansible.builtin.shell: "set -o pipefail && getent passwd {{ logs_toprm_chaperone_user }}  | awk -F: '{ print $6 }'"
  changed_when: false
  register: home_path
  become: true

- name: 'Install logstoprm cron .sh script.'
  ansible.builtin.template:
    src: logstoprm_cron.sh.j2
    dest: "{{ home_path }}/logstoprm_cron.sh"
    owner: root
    group: root
    mode: '0755'
  become: true
...
