---
- name: 'Install yum-utils, which provides the "needs-restarting" utility.'
  ansible.builtin.package:
    name: yum-utils
    state: latest
    update_cache: true
  become: true
- name: 'Update all installed packages (except Slurm and iRODS).'
  ansible.builtin.package:
    name: '*'
    state: latest
    update_cache: true
    exclude: 'slurm*,irods*' # These packages are version locked and we don't want to change that.
  notify: reboot_for_kernel_update
  become: true
- name: 'Install cron job to reboot server regularly to activate kernel updates.'
  ansible.builtin.cron:
    name: 'Reboot to load new kernel.'
    weekday: '2'
    minute: '45'
    hour: '4'
    user: root
    job: /bin/needs-restarting -r >/dev/null 2>&1 || /sbin/shutdown -r +60 "Restarting to apply updates..."
    cron_file: reboot
  when: inventory_hostname not in groups['cluster']|default([])
  become: true
...
