---
admin_ranges: "129.125.249.0/24,172.23.40.1/24"
ssh_host_signer_ca_keypair_dir: "ssh-host-ca"
ssh_host_signer_ca_private_key: "{{ ssh_host_signer_ca_keypair_dir }}/hpc-ca"
ssh_host_signer_key_types: '.*(rsa|ed25519).*'
ssh_host_signer_hostnames: "{{ ansible_fqdn }},{{ ansible_hostname }}{% for host in groups['jumphost'] %},{{ host }}+{{ ansible_hostname }}{% endfor %}"
spacewalk_server_url: 'http://spacewalk02.hpc.rug.nl/XMLRPC'
slurm_database_name: "{{ stack_prefix }}_slurm_accounting"
ai_jumphost: "{{ lookup('env','AI_PROXY') }}"
#
# Configure allowed network ports for geerlingguy.firewall role
#
firewall_allowed_tcp_ports:
  - '22'   # SSH
  - '9100'   # Node Exporter
#
# Local group specs.
# Note:
#  *  all local groups are listed here.
#  * In ../[name]-cluster/vars.yml we list which groups are created locally on which cluster.
#  * Never ever change nor recycle a GID value here unless you are in for a surprise...
#
auth_groups:
  admin:
    gid: 20000
  docker:
    gid: 20001
  users:
    gid: 20002
  depad:
    gid: 20003
  solve-rd:
    gid: 20004
  umcg-atd:
    gid: 20005
#
# Custom/extra yum repos
#
yum_repos:
  umcg-centos7:
    description: 'UMCG YUM repo for CentOS 7.'
    baseurl: http://spacewalk02.hpc.rug.nl/umcg-centos7
...
