---
admin_ranges: "129.125.249.0/24,172.23.40.1/24"
ssh_host_signer_ca_keypair_dir: "ssh-host-ca"
ssh_host_signer_ca_private_key: "{{ ssh_host_signer_ca_keypair_dir }}/{{ stack_name }}-ca"
ssh_host_signer_key_types: '.*(rsa|ed25519).*'
ssh_host_signer_hostnames: "{{ inventory_hostname }}\
    {% if ansible_fqdn is defined and ansible_fqdn != inventory_hostname %}\
      ,{{ ansible_fqdn }}\
    {% endif %}\
    {% for host in groups['jumphost'] | default([]) %}\
      ,{{ host }}+{{ inventory_hostname }}\
    {% endfor %}\
    {% for external_jumphost in external_jumphosts | default([])
       | map(attribute='hosts') | flatten
       | map(attribute='hostname') %}\
      ,{{ external_jumphost }}+{{ inventory_hostname }}\
    {% endfor %}"
slurm_database_name: "{{ stack_prefix }}_slurm_accounting"
ai_jumphost: "{{ lookup('env','AI_PROXY') }}"
#
# Local volume size (root partition) for all instances
#
local_volume_size_root: 33

#
# Public keys of all local admins.
#
public_keys_of_local_admins: "{{ local_admin_users | map('extract', auth_users) \
    | rejectattr('pub_keys', 'none') | rejectattr('pub_keys', 'undefined') \
    | map(attribute='pub_keys') \
    | map('regex_findall', '^([^\\n]+)', 'multiline=True') | flatten }}"

#
# Local group specs.
# Note:
#  * All local groups are listed here.
#  * In ../[stack_name]/vars.yml we list which groups are created locally on which stack.
#  * Never ever change nor recycle a GID value here unless you are in for a surprise...
#
auth_groups:
  admin:
    gid: 20000
  docker:
    gid: 20001
  users:
    gid: 20002
  depad:
    gid: 20003
  solve-rd:
    gid: 20004
  umcg-atd:
    gid: 20005
  funad:
    gid: 20006
  umcg-gap:
    gid: 20007
  umcg-gd:
    gid: 20008
  umcg-genomescan:
    gid: 20009
  umcg-gsad:
    gid: 20010
  umcg-gst:
    gid: 20011
  umcg-vipt:
    gid: 20012
  umcg-depad:
    gid: 20013
  umcg-funad:
    gid: 20014
  umcg-funus:
    gid: 20015
  umcg-labgnkbh:
    gid: 20016
  umcg-patho:
    gid: 20017
  umcg-lab:
    gid: 20018
  vipt:
    gid: 20019
  MEDGEN-NFG GCC Analyse Team:
    gid: 4560734
#
# Default for a group of users that are only allowd to transfer data.
# Is used by the sshd role and listed in
#     roles/sshd/defaults/main.yml,
# but that file is not used when the
#     roles/sshd/templates/sshd_config
# is redeployed by other roles like the ldap or sssd roles.
# Therefore we set a default here too.
#
data_transfer_only_group: sftp-only
#
# Pulp repos.
#
pulp_repos:
  centos7:
    - name: centos7-base
      description: 'CentOS-7 - Base.'
      remote_url: http://mirror.centos.org/centos/7/os/x86_64/
      client_baseurl: "https://{{ stack_prefix }}-repo/pulp/content/{{ stack_name | regex_replace('_cluster$', '') }}/centos7-base/"
    - name: centos7-updates
      description: 'CentOS-7 - Updates.'
      remote_url: http://mirror.centos.org/centos/7/updates/x86_64/
      client_baseurl: "https://{{ stack_prefix }}-repo/pulp/content/{{ stack_name | regex_replace('_cluster$', '') }}/centos7-updates/"
    - name: centos7-extras
      description: 'CentOS-7 - Extras.'
      remote_url: http://mirror.centos.org/centos/7/extras/x86_64/
      client_baseurl: "https://{{ stack_prefix }}-repo/pulp/content/{{ stack_name | regex_replace('_cluster$', '') }}/centos7-extras/"
    - name: epel7
      description: 'Extra Packages for Enterprise Linux 7 (EPEL).'
      remote_url: https://download.fedoraproject.org/pub/epel/7/x86_64/
      client_baseurl: "https://{{ stack_prefix }}-repo/pulp/content/{{ stack_name | regex_replace('_cluster$', '') }}/epel7/"
    - name: cpel7
      description: 'UMCG Custom Packages for Enterprise Linux 7 (CPEL).'
      #remote_url: no remote for our homebrew packages.
      client_baseurl: "https://{{ stack_prefix }}-repo/pulp/content/{{ stack_name | regex_replace('_cluster$', '') }}/cpel7/"
    - name: irods7
      description: 'RENCI iRODS Repository for Enterprise Linux 7.'
      remote_url: https://packages.irods.org/yum/pool/centos7/x86_64/
      client_baseurl: "https://{{ stack_prefix }}-repo/pulp/content/{{ stack_name | regex_replace('_cluster$', '') }}/irods7/"
    - name: lustre7
      description: 'Lustre client Long Term Support (LTS) releases for Enterprise Linux 7.'
      remote_url: https://downloads.whamcloud.com/public/lustre/latest-2.12-release/el7/client/
      client_baseurl: "https://{{ stack_prefix }}-repo/pulp/content/{{ stack_name | regex_replace('_cluster$', '') }}/lustre7/"
    - name: e2fsprogs7  # Dependency for Lustre project quota.
      description: 'Ext filesystem utility releases for Enterprise Linux 7.'
      remote_url: https://downloads.whamcloud.com/public/e2fsprogs/latest/el7/
      client_baseurl: "https://{{ stack_prefix }}-repo/pulp/content/{{ stack_name | regex_replace('_cluster$', '') }}/e2fsprogs7/"
    - name: ltb7
      description: 'LTB (LDAP Tool Box) project OpenLDAP packages for Enterprise Linux 7.'
      remote_url: https://ltb-project.org/rpm/openldap25/7/x86_64/
      client_baseurl: "https://{{ stack_prefix }}-repo/pulp/content/{{ stack_name | regex_replace('_cluster$', '') }}/ltb7/"
    - name: rsyslog7
      description: 'Rsyslog (Adiscon CentOS7 for x86_64)'
      remote_url: http://rpms.adiscon.com/v8-stable/epel-7/x86_64/
      client_baseurl: "https://{{ stack_prefix }}-repo/pulp/content/{{ stack_name | regex_replace('_cluster$', '') }}/rsyslog7/"
#
# List of repos for machines that do not use Pulp.
#
yum_repos:
  centos7:
    - file: centos7-base.repo
      id: centos7-base
      name: 'CentOS-7 - Base.'
      baseurl: http://mirror.centos.org/centos/7/os/x86_64/
      enabled: 1
      gpgcheck: 1
      gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7'
    - file: centos7-updates.repo
      id: centos7-updates
      name: 'CentOS-7 - Updates.'
      baseurl: http://mirror.centos.org/centos/7/updates/x86_64/
      enabled: 1
      gpgcheck: 1
      gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7'
    - file: centos7-extras.repo
      id: centos7-extras
      name: 'CentOS-7 - Extras.'
      baseurl: http://mirror.centos.org/centos/7/extras/x86_64/
      enabled: 1
      gpgcheck: 1
      gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7'
    - file: epel7.repo
      id: epel7
      name: 'Extra Packages for Enterprise Linux 7 (EPEL).'
      baseurl: https://download.fedoraproject.org/pub/epel/7/x86_64/
      enabled: 1
      gpgcheck: 1
      gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7' # comes preinstalled with epel-release
    - file: irods7.repo
      id: irods7
      name: 'RENCI iRODS Repository for Enterprise Linux 7.'
      baseurl: https://packages.irods.org/yum/pool/centos7/x86_64/
      enabled: 1
      gpgcheck: 0
    - file: lustre7.repo
      id: lustre7
      name: 'Lustre client Long Term Support (LTS) releases for Enterprise Linux 7.'
      baseurl: https://downloads.whamcloud.com/public/lustre/latest-2.12-release/el7/client/
      enabled: 1
      gpgcheck: 0
    - file: e2fsprogs7.repo
      id: e2fsprogs7  # Dependency for Lustre project quota.
      name: 'Ext filesystem utility releases for Enterprise Linux 7.'
      baseurl: https://downloads.whamcloud.com/public/e2fsprogs/latest/el7/
      enabled: 1
      gpgcheck: 0
    - file: ltb.repo
      id: ltb7
      name: 'LTB (LDAP Tool Box) project OpenLDAP packages for Enterprise Linux 7.'
      baseurl: https://ltb-project.org/rpm/openldap25/7/x86_64/
      enabled: 1
      gpgcheck: 0
    - file: rsyslog7.repo
      id: rsyslog7
      name: 'Rsyslog (Adiscon CentOS7 for x86_64)'
      baseurl: http://rpms.adiscon.com/v8-stable/epel-7/x86_64/
      enabled: 1
      gpgcheck: 0
  rocky9:
    - file: rocky.repo
      id: baseos
      enabled: 1
      gpgcheck: 1
    - file: rocky.repo
      id: baseos-debug
      enabled: 0
    - file: rocky.repo
      id: baseos-source
      enabled: 0
    - file: rocky.repo
      id: appstream
      enabled: 1
      gpgcheck: 1
    - file: rocky.repo
      id: appstream-debug
      enabled: 0
    - file: rocky.repo
      id: appstream-source
      enabled: 0
    - file: rocky.repo
      id: crb
      enabled: 1
      gpgcheck: 1
    - file: rocky.repo
      id: crb-debug
      enabled: 0
    - file: rocky.repo
      id: crb-source
      enabled: 0
    #
    # Rocky Addons
    #
    - file: rocky-addons.repo
      id: highavailability
      enabled: 0
    - file: rocky-addons.repo
      id: highavailability-debug
      enabled: 0
    - file: rocky-addons.repo
      id: highavailability-source
      enabled: 0
    - file: rocky-addons.repo
      id: resilientstorage
      enabled: 0
    - file: rocky-addons.repo
      id: resilientstorage-debug
      enabled: 0
    - file: rocky-addons.repo
      id: resilientstorage-source
      enabled: 0
    - file: rocky-addons.repo
      id: nfv
      enabled: 0
    - file: rocky-addons.repo
      id: nfv-debug
      enabled: 0
    - file: rocky-addons.repo
      id: nfv-source
      enabled: 0
    - file: rocky-addons.repo
      id: rt
      enabled: 0
    - file: rocky-addons.repo
      id: rt-debug
      enabled: 0
    - file: rocky-addons.repo
      id: rt-source
      enabled: 0
    - file: rocky-addons.repo
      id: sap
      enabled: 0
    - file: rocky-addons.repo
      id: sap-debug
      enabled: 0
    - file: rocky-addons.repo
      id: sap-source
      enabled: 0
    - file: rocky-addons.repo
      id: saphana
      enabled: 0
    - file: rocky-addons.repo
      id: saphana-debug
      enabled: 0
    - file: rocky-addons.repo
      id: saphana-source
      enabled: 0
    #
    # Rocky Devel
    #
    - file: rocky-devel.repo
      id: devel
      enabled: 0
    - file: rocky-devel.repo
      id: devel-debug
      enabled: 0
    - file: rocky-devel.repo
      id: devel-source
      enabled: 0
    #
    # Rocky Extras
    #
    - file: rocky-extras.repo
      id: extras
      enabled: 1
      gpgcheck: 1
    - file: rocky-extras.repo
      id: extras-debug
      enabled: 0
    - file: rocky-extras.repo
      id: extras-source
      enabled: 0
    - file: rocky-extras.repo
      id: plus
      enabled: 0
    - file: rocky-extras.repo
      id: plus-debug
      enabled: 0
    - file: rocky-extras.repo
      id: plus-source
      enabled: 0

#
#    - id: epel7
#      name: 'Extra Packages for Enterprise Linux 7 (EPEL).'
#      baseurl: https://download.fedoraproject.org/pub/epel/7/x86_64/
#      gpgcheck: 'true'
#      gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7' # comes preinstalled with epel-release
#    - id: irods7
#      name: 'RENCI iRODS Repository for Enterprise Linux 7.'
#      baseurl: https://packages.irods.org/yum/pool/centos7/x86_64/
#      gpgcheck: 'false'
#      gpgkey: ''
#    - id: lustre7
#      name: 'Lustre client Long Term Support (LTS) releases for Enterprise Linux 7.'
#      baseurl: https://downloads.whamcloud.com/public/lustre/latest-2.12-release/el7/client/
#      gpgcheck: 'false'
#      gpgkey: ''
#    - id: e2fsprogs7  # Dependency for Lustre project quota.
#      name: 'Ext filesystem utility releases for Enterprise Linux 7.'
#      baseurl: https://downloads.whamcloud.com/public/e2fsprogs/latest/el7/
#      gpgcheck: 'false'
#      gpgkey: ''
#    - id: ltb7
#      name: 'LTB (LDAP Tool Box) project OpenLDAP packages for Enterprise Linux 7.'
#      baseurl: https://ltb-project.org/rpm/openldap25/7/x86_64/
#      gpgcheck: 'false'
#      gpgkey: ''
#    - id: rsyslog7
#      name: 'Rsyslog (Adiscon CentOS7 for x86_64)'
#      baseurl: http://rpms.adiscon.com/v8-stable/epel-7/x86_64/
#      gpgcheck: 'false'
#      gpgkey: ''



# Iptables additional configurations 
iptables_extras_dir: '/etc/iptables_extras.d/'
...
