# Default iRODS setup info
irods_ssl_certificate_chain_file: "default.crt"
irods_ssl_certificate_key_file: "default.key"
irods_ssl_dh_params_file: "default-dhparams.pem"
irods_zone: 'myzone'                        # default main iRODS zone name
irods_local_resource: 'demoResc'            # local iRODS resource
irods_vault_path: '/var/lib/irods/Vault'    # default path to store files for local resource
irods_default_resource: 'someDefaultRes'    # default resource iRODS uploads to
irods_service_account: 'irods'              # linux account under which iRODS runs
irods_admin_name: 'rods'                    # iRODS (and zone) account
irods_admin_home_path: '/myzone/home/rods'  # iRODS admin's home path
server_type: 'icat'                         # iRODS Server Type
irods_db_user: '{{ irods_service_account }}'  # db Username, usually same as irods_service_account
irods_db_server: '127.0.0.1'                  # iRODS Database Server
irods_db_name: 'ICAT'                         # iRODS Database Name
remote_psql_server_ca: "remote_psql_server_ca.crt"   # (optional) remote servers's CA certificate
