---
ip_addresses:
  betabarrel:
    bb_internal_management:
      address: 192.168.122.193
      netmask: /32
#    bb_internal_storage:
#      address: 10.10.2.192
#      netmask: /32
  porch:
    bb_internal_management:
      address: 10.10.1.148
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    vlan16:
      address: 195.169.22.170
      netmask: /32
      fqdn: 'NXDOMAIN'
...
