---
- name: Restart slapd-ltb.service (OpenLDAP server).
  ansible.builtin.systemd:
    name: slapd-ltb.service
    state: restarted
    daemon_reload: true
  become: true
  listen: restart_slapd
...
