---
- name: Add public keys from CAs that signed {{ stack_name }} host keys to /etc/ssh/ssh_known_hosts.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/ssh_known_hosts
    mode: '0644'
    owner: root
    group: root
    create: true
    insertbefore: BOF
    regexp: "(?i)^#?@cert-authority .* for {{ stack_name }}$"
    line: "@cert-authority * {{ lookup('file', ssh_host_signer_ca_private_key + '.pub') }} for {{ stack_name }}"
  become: true

- name: Make sure /etc/ssh/ssh_config.d/*.conf config files are included.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/ssh_config
    mode: '0644'
    owner: root
    group: root
    create: false
    insertafter: EOF
    regexp: "(?i)^#?Include /etc/ssh/ssh_config.d/.*$"
    line: 'Include /etc/ssh/ssh_config.d/*.conf'
  become: true

- name: 'Configure ssh client for external stack.'
  ansible.builtin.include_tasks:
    file: configure_ssh_client_for_external_stack.yml
  vars:
    external_stack: "{{ item }}"
  when:
    - ssh_client_configs is defined
    - inventory_hostname in groups['jumphost'] | default([]) or
      inventory_hostname in groups['cluster'] | default([])
  loop: "{{ ssh_client_configs }}"
...
