---
- block:
    - name: "Get list of {{ group }} subgroups with version number from the LDAP."
      shell: |
        ldapsearch -LLL -D '{{ ldap_binddn }}' -w '{{ bindpw }}' -b '{{ ldap_base }}' -H '{{ ldap_uri }}' \
            "(ObjectClass=GroupofNames)" dn \
          | tr "=," "\n" \
          | fgrep "{{ group }}" \
          | grep -v "^{{ group }}$" \
          | grep -- "-v[0-9][0-9]*$" \
          || true
      register: versioned_subgroups
    - set_fact: # noqa 502
        versioned_subgroups_list: "{% if versioned_subgroups.stdout | length %}{{ versioned_subgroups.stdout.split('\n') | list }}{% endif %}"

- block:
    - name: "Get list of {{ group }} subgroups without version number and excluding *-dms groups from the LDAP."
      shell: |
        ldapsearch -LLL -D '{{ ldap_binddn }}' -w '{{ bindpw }}' -b '{{ ldap_base }}' -H '{{ ldap_uri }}' \
            "(ObjectClass=GroupofNames)" dn \
            | tr "=," "\n" \
            | fgrep "{{ group }}" \
            | grep -v "^{{ group }}$" \
            | grep -v -- "-v[0-9][0-9]*$\|-dms$" \
            || true
      register: unversioned_subgroups
    - set_fact: # noqa 502
        unversioned_subgroups_list: "{% if unversioned_subgroups.stdout | length %}{{ unversioned_subgroups.stdout.split('\n') | list }}{% endif %}"

- name: "Create directory structure for releases with version number on {{ lfs }}."
  block:
    - name: "Create /groups/{{ group }}/{{ lfs }}/releases/ directory."
      file:
        path: "/groups/{{ group }}/{{ lfs }}/releases/"
        owner: "{{ group }}-dm"
        group: "{{ group }}"
        mode: "{{ mode_dataset }}"
        state: 'directory'
    - name: "Create /groups/{{ group }}/{{ lfs }}/releases/${dataset} directory."
      file:
        path: "/groups/{{ group }}/{{ lfs }}/releases/{{ item | regex_replace('^' + group + '-(.*)-(v[0-9][0-9]*)$', '\\1') }}"
        owner: "{{ group }}-dm"
        group: "{{ group }}"
        mode: "{{ mode_dataset }}"
        state: 'directory'
      with_items: "{{ versioned_subgroups_list }}"
    - name: "Create /groups/{{ group }}/{{ lfs }}/releases/${dataset}/${version} directory."
      file:
        path: "/groups/{{ group }}/{{ lfs }}/releases/\
               {{ item | regex_replace('^' + group + '-(.*)-(v[0-9][0-9]*)$', '\\1') }}/\
               {{ item | regex_replace('^' + group + '-(.*)-(v[0-9][0-9]*)$', '\\2') }}"
        owner: "{{ group }}-dm"
        group: "{% if item | length %}{{ item }}{% else %}{{ group }}{% endif %}"
        mode: "{{ mode_version }}"
        state: 'directory'
      with_items: "{{ versioned_subgroups_list }}"
      ignore_errors: yes # Continue of this specific subgroup failed and try to create other subgroup folders.
  when: versioned_subgroups_list | length > 0
  become: true
  become_user: "{{ group }}-dm"

- name: "Create directory structure for projects on {{ lfs }}."
  block:
    - name: "Create /groups/{{ group }}/{{ lfs }}/projects directory."
      file:
        path: "/groups/{{ group }}/{{ lfs }}/projects/"
        owner: "{{ group }}-dm"
        group: "{{ group }}"
        mode: "{{ mode_project }}"
        state: 'directory'
    - name: "Create /groups/{{ group }}/{{ lfs }}/projects/${project} directory."
      file:
        path: "/groups/{{ group }}/{{ lfs }}/projects/{{ item | regex_replace('^' + group + '-(.*)$', '\\1') }}"
        owner: "{{ group }}-dm"
        group: "{% if item | length %}{{ item }}{% else %}{{ group }}{% endif %}"
        mode: "{{ mode_project }}"
        state: 'directory'
      with_items: "{{ unversioned_subgroups_list }}"
      ignore_errors: yes # Continue of this specific subgroup failed and try to create other subgroup folders.
  when: unversioned_subgroups_list | length > 0
  become: true
  become_user: "{{ group }}-dm"
...
