---
- name: "Create directory structure for releases with version number."
  when: versioned_sub_groups | length > 0
  become: true
  become_user: "{{ main_group }}-dm"
  block:
    - name: "Create {{ lfs_path }}/releases/ directory."
      ansible.builtin.file:
        path: "{{ lfs_path }}/releases/"
        owner: "{{ main_group }}-dm"
        group: "{{ main_group }}"
        mode: '2750'
        state: 'directory'
    - name: "Create {{ lfs_path }}/releases/${dataset} directory."
      ansible.builtin.file:
        path: "{{ lfs_path }}/releases/{{ item }}"
        owner: "{{ main_group }}-dm"
        group: "{{ main_group }}"
        mode: "{{ mode_dataset }}"
        state: 'directory'
      with_items: "{{ versioned_sub_groups | map('regex_replace', '^' + main_group + '-(.*)-(v[0-9][0-9]*)$', '\\1') | unique }}"
    - name: "Create {{ lfs_path }}/releases/${dataset}/${version} directory."
      ansible.builtin.file:
        path: "{{ lfs_path }}/releases/\
               {{ item | regex_replace('^' + main_group + '-(.*)-(v[0-9][0-9]*)$', '\\1') }}/\
               {{ item | regex_replace('^' + main_group + '-(.*)-(v[0-9][0-9]*)$', '\\2') }}"
        owner: "{{ main_group }}-dm"
        group: "{% if item | length %}{{ item }}{% else %}{{ main_group }}{% endif %}"
        mode: "{{ mode_version }}"
        state: 'directory'
      with_items: "{{ versioned_sub_groups }}"
      # Continue if this specific subgroup failed and try to create other subgroup folders.
      ignore_errors: true  # noqa ignore-errors

- name: "Create directory structure for projects on."
  when: unversioned_sub_groups | length > 0
  become: true
  become_user: "{{ main_group }}-dm"
  block:
    - name: "Create {{ lfs_path }}/projects directory."
      ansible.builtin.file:
        path: "{{ lfs_path }}/projects/"
        owner: "{{ main_group }}-dm"
        group: "{{ main_group }}"
        mode: '2750'
        state: 'directory'
    - name: "Create {{ lfs_path }}/projects/${project} directory."
      ansible.builtin.file:
        path: "{{ lfs_path }}/projects/{{ item | regex_replace('^' + main_group + '-(.*)$', '\\1') }}"
        owner: "{{ main_group }}-dm"
        group: "{% if item | length %}{{ item }}{% else %}{{ main_group }}{% endif %}"
        mode: "{{ mode_project }}"
        state: 'directory'
      with_items: "{{ unversioned_sub_groups }}"
      # Continue if this specific subgroup failed and try to create other subgroup folders.
      ignore_errors: true  # noqa ignore-errors
...
