---
- name: Create a repository directory
  ansible.builtin.file:
    path: '{{ lyr_dir_path }}'
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Install a list of packages with a list variable
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
      - createrepo
      - yum-plugin-priorities
  become: true

- name: Deploy configuration .repo file into /etc/yum.repos.d/
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '0644'
  with_items:
    - {src: 'templates/local_yum.repo', dest: '/etc/yum.repos.d/'}
    - {src: 'templates/README', dest: '{{ lyr_dir_path }}'}
  become: true

- name: Build repository for the first time
  ansible.builtin.command:
    cmd: /usr/bin/createrepo {{ lyr_dir_path }}
    creates: '{{ lyr_dir_path }}/repodata/repomd.xml'
  register: cr_result
  failed_when:
    - cr_result.rc != 0
  become: true
...
