---
- name: Create a local yum repository
  ansible.builtin.include: lyr.yml
  when: local_yum_repository | bool is true

- name: Remove a local yum repository
  ansible.builtin.include: lyr_remove.yml
  when: local_yum_repository | bool is false
...
