---
#
# Determine cluster size based on
#  * number of vcompute nodes in inventory and
#  * cores per node, mem per node, etc. as specified in group_vars for cluster.
#
slurm_cluster_cores_total: "{{ groups['compute_vm'] | map('extract', hostvars, 'slurm_max_cpus_per_node') | map('int') | sum }}"
slurm_cluster_mem_total: "{{ groups['compute_vm'] | map('extract', hostvars, 'slurm_max_mem_per_node') | map('int') | sum }}"
#
# Determine max resources that can be consumed by an interactive job in QoS 'interactive'
#  * Use half of the total cores of the smallest node with a minimum of 1
#  * Use half of the total memory of the smallest node with a minimum of 1000.
#
slurm_total_cores_of_smallest_node: "{{ groups['compute_vm'] | map('extract', hostvars, 'slurm_max_cpus_per_node') | map('int') | min }}"
slurm_total_mem_of_smallest_node: "{{ groups['compute_vm'] | map('extract', hostvars, 'slurm_max_mem_per_node') | map('int') | min }}"
slurm_interactive_max_cores_per_user: "{{ [1, (slurm_total_cores_of_smallest_node | float * 0.5) | int] | max }}"
slurm_interactive_max_mem_per_user: "{{ [1000, (slurm_total_mem_of_smallest_node | float * 0.5) | int] | max }}"
...
