---
- name: Copy XML project configuration file to destination folder
  become: true
  ansible.builtin.template:
    src: config.xml
    dest: "{{ jenkins_xml_dest }}/{{ item }}_config.xml"
    owner: jenkins
    group: jenkins
    mode: '0755'
  loop: "{{ jenkins_projects }}"

- name: Get a list of existing Jenkins projects
  ansible.builtin.shell:
    cmd: |
         java -jar {{ jenkins_cli_dest }} \
         -s {{ jenkins_url }} \
         -auth {{ jenkins_admin_username }}:{{ jenkins_admin_api_token }} \
         list-jobs
  register: existing_jenkins_jobs

- name: Update jobs of existing Jenkins projects
  ansible.builtin.shell:
    cmd: |
         java -jar {{ jenkins_cli_dest }} \
         -s {{ jenkins_url }} \
         -auth {{ jenkins_admin_username }}:{{ jenkins_admin_api_token }} \
         update-job "{{ item }}" < "{{ jenkins_xml_dest }}/{{ item }}_config.xml"
  loop: "{{ jenkins_projects }}"
  when: item in "{{ existing_jenkins_jobs.stdout_lines }}"


- name: Create Jenkins project if it does not exist yet
  ansible.builtin.shell:
    cmd: |
         java -jar {{ jenkins_cli_dest }} \
         -s {{ jenkins_url }} \
         -auth {{ jenkins_admin_username }}:{{ jenkins_admin_api_token }} \
         create-job "{{ item }}" < "{{ jenkins_xml_dest }}/{{ item }}_config.xml"
  loop: "{{ jenkins_projects }}"
  when: item not in "{{ existing_jenkins_jobs.stdout_lines }}"
...
