---
- name: Configure ldap with ldif files
  ansible.builtin.command:
    cmd: >
      /usr/local/openldap/bin/ldapadd -x -H "ldap://localhost"
      -D "{{ ldap_credentials['stack']['admin']['dn'] }}"
      -w "{{ ldap_credentials['stack']['admin']['pw'] }}"
      -f '/tmp/configure_lsaai-{{ item }}'
  with_items:
    - ldap_groups_ou.ldif
    - ldap_users_ou.ldif
  register: lsaai_ldapadd_result
  failed_when: false
  changed_when: lsaai_ldapadd_result.rc == 0
  become: true
  become_user: lsaai
  listen: lsaai_ldapadd
...
