---
#
# ICMP (only inbound; outbound ICMP is allowed without restrictions).
#
iptables_allow_icmp_inbound:
  - ANY
#
# HTTP and HTTPS inbound. (HTTP and HTTPS always allowed by default to fetch packages from repos.)
#
iptables_allow_http_inbound: []
iptables_allow_https_inbound: []
#
# SSH.
#
iptables_allow_ssh_inbound:
  - ANY
iptables_allow_ssh_outbound: []
#
# Public MySQL databases @ EBI (only outbound).
#
iptables_allow_ebi_mysql_outbound: []
#
# PostgreSQL (only outbound).
#
iptables_allow_postgresql_outbound: []
#
# FTP (only outbound).
#
iptables_allow_ftp_outbound: []
#
# Aspera (only outbound).
#
iptables_allow_aspera_outbound: []
#
# iRODS: by definition both inbound and outbound.
#
iptables_allow_irods: []
#
# Globus ToolKit (only outbound).
#
iptables_allow_globus_outbound: []
#
# Log dropped packets only for debugging to prevent flooding logs!
#
iptables_log_dropped_packets: false
#
# Set to true (default) to ensure other iptables management software is disabled.
#
iptables_disable_firewalld: true
...
