---
#
# ICMP (only inbound; outbound ICMP is allowed without restrictions).
# 
iptables_allow_icmp_inbound:
  - ANY
#
# HTTPS
#
iptables_allow_https_inbound: []
#
# SSH.
#
iptables_allow_ssh_inbound:
  - ANY
iptables_allow_ssh_outbound:
  - ANY
#
# Public MySQL databases @ EBI (only outbound).
#
iptables_allow_ebi_mysql_outbound: []
#
# FTP (only outbound).
#
iptables_allow_ftp_outbound: []
#
# Aspera (only outbound). 
#
iptables_allow_aspera_outbound: []
#
# Globus ToolKit (only outbound).
#
iptables_allow_globus_outbound: []
#
# Log dropped packets only for debugging to prevent flooding logs!
#
iptables_log_dropped_packets: false
#
# Set to true to ensure other iptables management software is disabled.
#
iptables_disable_firewalld: true
iptables_disable_ufw: true
...
