---
- name: Install dependencies to interface with MariaDB/MySQL databases/services.
  ansible.builtin.package:
    name:
      - python3-PyMySQL
    state: latest
    update_cache: true
  become: true
...
