---
- name: Configure fail2ban.
  ansible.builtin.include_tasks: fail2ban.yml
  when: basic_security_fail2ban_enabled | bool

- name: Configure SSH and sudo.
  ansible.builtin.include_tasks: ssh.yml

- name: Configure automatic updates.
  ansible.builtin.include_tasks: autoupdate.yml
  when: basic_security_autoupdate_enabled | bool
...
