---
use_ldap: true  # needed for the sshd template
#
# Example of structure of ldap_domains variable in group_vars/.../vars.yml
#
# ldap_domains:
#  stack:
#    uri: ''
#    base: ''
#    schema: rfc2307
#    min_id: 10000
#    max_id: ''
#    user_object_class: posixAccount
#    user_ssh_public_key_attr: sshPublicKey
#    group_object_class: ''
#    group_quota_soft_limit_template: ''
#    group_quota_hard_limit_template: ''
#
# Example of structure of ldap_credentials variable in group_vars/.../secrets.yml
# At least a read-only account is required to query the LDAP.
# If we do not use an external LDAP and need to create one ourselves a read-write admin account is reauired to manage the LDAP content too.
#
# ldap_credentials:
#   stack:
#     readonly:
#       dn: 'cn=readonly,....'
#       pw: '....'
#       hash: '{ARGON2}$argon2id$v=19$m=65536,t=2,p=1$.....'
#     admin:
#       dn: 'cn=admin,....'
#       pw: '....'
#       hash: '{ARGON2}$argon2id$v=19$m=65536,t=2,p=1$....'
...
