---
- name: 'Install NHC.'
  ansible.builtin.package:
    state: latest
    update_cache: true
    name:
      - lbnl-nhc
  become: true

- name: 'Create files & folders for NHC.'
  ansible.builtin.file:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  loop:
    - name: '/etc/nhc'
      owner: root
      group: root
      mode: '0755'
      state: directory
    - name: '/var/run/nhc'
      owner: root
      group: root
      mode: '0700'
      state: directory
  become: true

- name: 'Deploy config files.'
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - src: 'templates/nhc_standalone.conf'
      dest: '/etc/nhc/nhc.conf'
    - src: 'templates/nhc_standalone.sysconfig'
      dest: '/etc/sysconfig/nhc'
  become: true
...
