---
ip_addresses:
  earl1:
    logs_internal_management:
      address: 10.10.1.158
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    vlan16:
      address: 195.169.22.151
      netmask: /32
      fqdn: 'NXDOMAIN'
  earl2:
    logs_external:
      address: 10.10.1.4
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    logs_external_public:
      address: 40.68.28.44
      netmask: /32
      fqdn: 'logs-earl2-ad5f.westeurope.cloudapp.azure.com'
  earl3:
    logs_external:
      address: 10.10.1.5
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    logs_external_public:
      address: 40.68.28.187
      netmask: /32
      fqdn: 'logs-earl3-ad5f.westeurope.cloudapp.azure.com'
  earl4:
    logs_internal_management:
      address: 10.10.1.62
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    vlan16:
      address: 195.169.22.180
      netmask: /32
      fqdn: 'NXDOMAIN'
  earl5:
    logs_internal_management:
      address: 10.10.1.251
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    vlan16:
      address: 195.169.22.177
      netmask: /32
      fqdn: 'NXDOMAIN'
  earl6:
    logs_internal_management:
      address: 10.10.1.4
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    logs_internal_management_public:
      address: 13.81.87.11
      netmask: /32
      fqdn: 'logs-earl6-6b85.westeurope.cloudapp.azure.com'
  logs_internal_management-vlan16-router:
    logs_internal_management:
      address: 10.10.1.1
      netmask: /32
    vlan16:
      address: 195.169.22.175
      netmask: /32
      fqdn: 'NXDOMAIN'
...
