version: '2'
services:
  davrods:
    network_mode: 'host'
    ports:
      - '443:443'
    build:
      context: ./
      args:
        - ENV_DAVRODS_IRODS_VERSION
        - ENV_DAVRODS_VERSION
    restart: always
