---
- name: 'Make sure we have a parent entry for users.'
  community.general.ldap_entry:
    dn: "ou=users,{{ regular_users_ldap_base }}"
    objectClass: 'organizationalUnit'
    server_uri: "{{ regular_users_ldap_server_uri }}"
    bind_dn: "{{ regular_users_ldap_bind_dn }}"
    bind_pw: "{{ regular_users_ldap_bind_pw }}"

- name: 'Make sure we have a parent entry for groups.'
  community.general.ldap_entry:
    dn: "ou=groups,{{ regular_users_ldap_base }}"
    objectClass: 'organizationalUnit'
    server_uri: "{{ regular_users_ldap_server_uri }}"
    bind_dn: "{{ regular_users_ldap_bind_dn }}"
    bind_pw: "{{ regular_users_ldap_bind_pw }}"

- name: 'Add regular groups to parent entry for groups.'
  community.general.ldap_entry:
    dn: "cn={{ item }},ou=groups,{{ regular_users_ldap_base }}"
    objectClass:
      - 'groupOfMembers'
      - 'posixGroup'
    state: present
    attributes:
      gidNumber: "{{ auth_groups[item].gid }}"
    server_uri: "{{ regular_users_ldap_server_uri }}"
    bind_dn: "{{ regular_users_ldap_bind_dn }}"
    bind_pw: "{{ regular_users_ldap_bind_pw }}"
  with_items: "{{ regular_groups }}"

- name: 'Add private groups for home dirs of users to parent entry for groups.'
  community.general.ldap_entry:
    dn: "cn={{ item.user }},ou=groups,{{ regular_users_ldap_base }}"  # Use same name as user's account name for user's private group.
    objectClass: 'posixGroup'
    state: present
    attributes:
      gidNumber: "{{ auth_users[item.user].uid }}"  # Use same GID as user's UID for user's private group.
    server_uri: "{{ regular_users_ldap_server_uri }}"
    bind_dn: "{{ regular_users_ldap_bind_dn }}"
    bind_pw: "{{ regular_users_ldap_bind_pw }}"
  with_items: "{{ regular_users }}"

- name: 'Add users to parent entry for users.'
  community.general.ldap_entry:
    dn: "cn={{ item.user }},ou=users,{{ regular_users_ldap_base }}"
    state: present
    objectClass:
      - 'inetOrgPerson'
      - 'posixAccount'
      - 'top'
      - 'ldapPublicKey'
    attributes:
      sn: "{{ item.user }}"
      givenName: "{{ auth_users[item.user].comment }}"
      cn: "{{ item.user }}"
      uid: "{{ item.user }}"
      uidNumber: "{{ auth_users[item.user].uid }}"
      gidNumber: "{{ auth_users[item.user].uid }}"  # primary group == private group for user.
      homeDirectory: "/home/{{ item.user }}"
      loginShell: '/bin/bash'
      sshPublicKey: "{{ auth_users[item.user].pub_keys }}"
      mail: "{{ auth_users[item.user].email }}"
    server_uri: "{{ regular_users_ldap_server_uri }}"
    bind_dn: "{{ regular_users_ldap_bind_dn }}"
    bind_pw: "{{ regular_users_ldap_bind_pw }}"
  with_items: "{{ regular_users }}"

- name: 'Update user attributes.'
  community.general.ldap_attrs:
    dn: "cn={{ item.user }},ou=users,{{ regular_users_ldap_base }}"
    state: exact
    attributes:
      sshPublicKey: "{{ auth_users[item.user].pub_keys }}"
      mail: "{{ auth_users[item.user].email }}"
      #
      # The to_json(ensure_ascii=True) filter is a temporary hack to remove non ASCII characters,
      # which are not supported in the gecos attribute from the RFC2307 schema.
      # We can use all characters in the gecos field once we switch to the RFC2307bis schema, which uses UTF-8.
      #
      gecos: "{{ auth_users[item.user].comment | to_json(ensure_ascii=True) }}\
              {% if auth_users[item.user].email is defined and auth_users[item.user].email | length %} <{{ auth_users[item.user].email }}>{% endif %}"
    server_uri: "{{ regular_users_ldap_server_uri }}"
    bind_dn: "{{ regular_users_ldap_bind_dn }}"
    bind_pw: "{{ regular_users_ldap_bind_pw }}"
  with_items: "{{ regular_users }}"

- name: 'Add users to groups.'
  community.general.ldap_attrs:
    dn: "cn={{ item.1 }},ou=groups,{{ regular_users_ldap_base }}"
    state: present
    attributes:
      memberUid: "{{ item.0.user }}"
    server_uri: "{{ regular_users_ldap_server_uri }}"
    bind_dn: "{{ regular_users_ldap_bind_dn }}"
    bind_pw: "{{ regular_users_ldap_bind_pw }}"
  with_subelements:
    - "{{ regular_users }}"
    - 'groups'
...
