---
#
# Old style config for Dockerized OpenLDAP.
#
- name: 'Create regular users & groups in LDAP.'
  include_tasks:
    file: ldap_regular_users.yml
  vars:
    regular_users_ldap_base: "{{ ldap_base }}"
    regular_users_ldap_bind_dn: "{{ ldap_binddn }}"
    regular_users_ldap_bind_pw: "{{ bindpw }}"
    regular_users_ldap_server_uri: "{{ ldap_uri }}"
  when:
    - use_ldap | default(true) | bool
    - create_ldap | default(false) | bool
    - inventory_hostname in groups['ldap_server'] | default([])

#
# New style config for native OpenLDAP.
#
- name: 'Create regular users & groups in LDAP.'
  include_tasks:
    file: ldap_regular_users.yml
  vars:
    regular_users_ldap_base: "{{ ldap_domains['stack']['base'] }}"
    regular_users_ldap_bind_dn: "{{ ldap_credentials['stack']['admin']['dn'] }}"
    regular_users_ldap_bind_pw: "{{ ldap_credentials['stack']['admin']['pw'] }}"
    regular_users_ldap_server_uri: "{{ ldap_domains['stack']['uri'] }}"
  when:
    - use_ldap | default(true) | bool
    - ldap_domains['stack']['create_ldap'] | default(false) | bool
    - inventory_hostname in groups['ldap_server'] | default([])

- name: 'Create local regular users & groups.'
  include_tasks:
    file: local_regular_users.yml
  when:
    - not use_ldap | default(true) | bool
    - inventory_hostname in groups['cluster'] | default([]) or
      inventory_hostname in groups['jumphost'] | default([]) or
      inventory_hostname in groups['chaperone'] | default([]) or
      inventory_hostname in groups['data_transfer'] | default([])
...
