---

- name: Create main backup directory
  ansible.builtin.file:
    path: '{{ main_backup_folder }}'
    state: directory
    mode: '0755'
  when: backup_clist is defined and backup_clist | default([]) | length > 0
  become: true

- name: Create backup subdirectories for each item from list
  ansible.builtin.file:
    path: '{{ main_backup_folder }}/{{ item.name }}/'
    state: directory
    mode: '0700'
  when: backup_clist is defined and backup_clist | default([]) | length > 0
  become: true
  loop: "{{ backup_clist }}"

- name: 'Install backup cronjob script'
  ansible.builtin.template:
    src: "templates/backup_cronjob.sh.j2"
    dest: '/root/backup_cronjob.sh'
    owner: 'root'
    group: 'root'
    mode: '0700'
  when: backup_clist is defined and backup_clist | default([]) | length > 0
  become: true

- name: 'Create cron for daily backup'
  ansible.builtin.cron:
    name: '{{ item.0.name }}-{{ item.1.name }} - do not change it manually!'
    hour: '{{ item.1.hour }}'
    minute: '{{ item.1.minute }}'
    month: '{{ item.1.month }}'
    weekday: '{{ item.1.weekday }}'
    user: 'root'
    disabled: '{{ item.1.disabled | default("true") }}'
    job: >
      /root/backup_cronjob.sh '{{ item.0.name }}' '{{ item.1.name }}' '{{ item.1.keep }}'
      '{{ item.0.src_path }}' '{{ main_backup_folder | default("/backups/", true) }}'
  loop: '{{ backup_clist | subelements("frequency") }}'
  become: true

...
