---
- name: Deploy rsyslog server
  ansible.builtin.include_tasks:
    file: rsyslog.yml
  when: inventory_hostname in groups['logs'] | default([])

- name: Configure logs collecting - logs to prm
  ansible.builtin.include_tasks:
    file: logs_to_prm.yml
  when: inventory_hostname in groups['logs'] | default([])
...
