---
- name: Get information on CA key from the repo
  ansible.builtin.stat:
    path: "{{ rsyslog_repository_dir }}/{{ rsyslog_ca_key_file }}"
  register: repo_rsyslog_ca_key
  delegate_to: localhost
  connection: local

- name: Get information on CA certificate from the repo
  ansible.builtin.stat:
    path: "{{ rsyslog_repository_dir }}/{{ rsyslog_ca_cert_file }}"
  register: repo_rsyslog_ca_cert
  delegate_to: localhost
  connection: local

- name: Get information on CA key from managed rsyslog server
  ansible.builtin.stat:
    path: "{{ rsyslog_remote_path_key_dir }}/{{ rsyslog_ca_key_file }}"
  register: rsyslog_ca_key_on_server
  become: true

- name: Get information on CA cert from managed rsyslog server
  ansible.builtin.stat:
    path: "{{ rsyslog_remote_path_cert_dir }}/{{ rsyslog_ca_key_file }}"
  register: rsyslog_ca_cert_on_server

- name: Install gnutls and newer openssl
  ansible.builtin.package:
    name:
      - gnutls
      - gnutls-utils
      - python-firewall
      - firewalld
      - openssl11
      - openssl11-devel
    state: latest
    update_cache: true
  become: true
  notify: restart-rsyslog.service

- name: Install rsyslog and gnutls with all plugins
  ansible.builtin.package:
    name:
      - rsyslog
      - librelp
      - rsyslog-relp
      - rsyslog-gnutls
    state: latest
    update_cache: true
    disablerepo: '*'
    enablerepo: 'rsyslog7'
  become: true
  notify: restart-rsyslog.service

- name: If rsyslog keys and certificate in repository and on server are missing, then create CA
  ansible.builtin.include_tasks: create_ca.yml
  run_once: true
  when:
    ( not repo_rsyslog_ca_key.stat.exists and not rsyslog_ca_key_on_server.stat.exists ) or
    ( not repo_rsyslog_ca_cert.stat.exists and not rsyslog_ca_cert_on_server.stat.exists)
  register: created_ca

- name: If CA key exists in repository, then deploy it
  ansible.builtin.copy:
    src: "{{ rsyslog_repository_dir }}/{{ rsyslog_ca_key_file }}"
    dest: "{{ rsyslog_remote_path_key_dir }}/{{ rsyslog_ca_key_file }}"
    mode: '0600'
    decrypt: true
    force: true
  become: true
  when: repo_rsyslog_ca_key.stat.exists
  notify: restart-rsyslog.service

- name: If CA certificate exists in repository, then deploy it
  ansible.builtin.copy:
    src: "{{ rsyslog_repository_dir }}/{{ rsyslog_ca_cert_file }}"
    dest: "{{ rsyslog_remote_path_cert_dir }}/{{ rsyslog_ca_cert_file }}"
    mode: '0644'
    decrypt: false
    force: true
  become: true
  when: repo_rsyslog_ca_cert.stat.exists
  notify: restart-rsyslog.service

- name: Fetch remote CA key to repository
  ansible.builtin.fetch:
    src: "{{ rsyslog_remote_path_key_dir }}/{{ rsyslog_ca_key_file }}"
    dest: "{{ rsyslog_repository_dir }}/"
    flat: true
    fail_on_missing: true
    validate_checksum: true
  when: not repo_rsyslog_ca_key.stat.exists or created_ca.changed # noqa no-handler
  become: true

- name: Fetch servers CA cert to repository
  ansible.builtin.fetch:
    src: "{{ rsyslog_remote_path_cert_dir }}/{{ rsyslog_ca_cert_file }}"
    dest: "{{ rsyslog_repository_dir }}/"
    flat: true
    fail_on_missing: true
    validate_checksum: true
  when: not repo_rsyslog_ca_cert.stat.exists or created_ca.changed # noqa no-handler
  become: true

- name: Create servers key and certificate
  ansible.builtin.include_tasks: server_certificate.yml
  register: created_certificate

- name: Checking if "Restart=always" is present in /usr/lib/systemd/system/rsyslog.service
  ansible.builtin.command:
    cmd: "grep 'Restart=always' /usr/lib/systemd/system/rsyslog.service"
  register: rsyslog_service_restart
  changed_when: false
  failed_when: rsyslog_service_restart.rc >= 2
  become: true

- name: Checking if "WatchdogSec=" is present in /usr/lib/systemd/system/rsyslog.service
  ansible.builtin.command:
    cmd: "grep 'WatchdogSec=' /usr/lib/systemd/system/rsyslog.service"
  register: rsyslog_service_watchdogsec
  changed_when: false
  failed_when: rsyslog_service_watchdogsec.rc >= 2
  become: true

- name: Configure the rsyslog service, to restart regardless of exit state
  ansible.builtin.lineinfile:
    path: '/usr/lib/systemd/system/rsyslog.service'
    backup: true
    insertafter: "[Service]"
    regexp: '^Restart=.*$'
    line: 'Restart=always'
    owner: root
    group: root
    mode: '0644'
  when:
    - "'Restart=always' not in rsyslog_service_restart.stdout"
  notify: reconfigure_rsyslog_service
  become: true

- name: Configure the rsyslog service, to restart after a day
  ansible.builtin.lineinfile:
    path: '/usr/lib/systemd/system/rsyslog.service'
    backup: true
    insertafter: '\[Service\]'
    state: present
    line: 'WatchdogSec=86400'           # 1 day = 86400 seconds
    owner: root
    group: root
    mode: '0644'
  when:
    - "'WatchdogSec=' not in rsyslog_service_watchdogsec.stdout"
  notify: reconfigure_rsyslog_service
  become: true

- name: Remove problematic /etc/rsyslog.d/listen.conf file
  ansible.builtin.file:
    path: /etc/rsyslog.d/listen.conf
    state: absent
  become: true
  notify: restart-rsyslog.service

- name: Add logrotate to compress and move old logs to subfolder called 'compressed_logs'
  ansible.builtin.template:
    src: templates/remote.logrotate
    dest: /etc/logrotate.d/remote
    mode: '0644'
    force: true
  become: true

- name: Deploy server rsyslog.conf
  ansible.builtin.template:
    src: templates/rsyslog.conf
    dest: /etc/rsyslog.conf
    force: true
    mode: '0644'
    validate: /sbin/rsyslogd -N1 -f %s
  become: true
  notify: restart-rsyslog.service

- name: Start and enable rsyslog service
  ansible.builtin.systemd:
    name: rsyslog.service
    state: started
    enabled: true
  become: true
...
