---
- name: Install packages with yum.
  yum:
    state: 'latest'
    update_cache: true
    name:
      - nano
      - httpie
      - jq
      - curl
  become: true

- name: Get checksum of Pulp root certificate on repo server.
  stat:
    path: "{{ pulp_root_cert_path_on_repo_server }}"
    checksum_algorithm: sha1
  register: repo_server_pulp_root_certificate
  become: true

- name: Checking if Pulp root certificate must be updated.
  debug:
    msg: |
         ***********************************************************************************************************
         IMPORTANT: Manual work!
                    The Pulp root certificate on the Pulp repo server in:
                        {{ pulp_root_cert_path_on_repo_server }}
                    Differs from the Pulp root certificate on the Ansible control host in:
                        {{ pulp_root_cert_path_on_control_host }}
                    Check which one is correct and update the other one.
         ***********************************************************************************************************
  when: repo_server_pulp_root_certificate.stat.checksum | default('Missing Pulp root certificate checksum on repo server', true) != 
        lookup('unvault', pulp_root_cert_path_on_control_host) | hash('sha1')
...