---
- name: 'Ensure that /etc/irods directory exists'
  ansible.builtin.file:
    dest: "/etc/irods"
    mode: '0755'
    state: directory
  become: true

- name: 'Gather status of /etc/irods certificates'
  ansible.builtin.stat:
    path: /etc/irods/{{ item }}
  loop:
    - '{{ ir_ssl_certificate_key_file | basename }}'
    - '{{ ir_ssl_certificate_chain_file | basename }}'
    - '{{ ir_ssl_dh_params_file }}'
  register: check_irods_certs

- name: 'Fail if certificates in /etc/irods do not exist'
  ansible.builtin.fail:
    msg: 'The file {{ item.item }} does not exists'
  loop: '{{ check_irods_certs.results }}'
  when: not item.stat.exists or not item.stat.rusr
  become: true

- name: 'Create davrods docker group'
  ansible.builtin.group:
    name: '{{ davrods_docker_user }}'
    state: present
  become: true

- name: 'Create davrods docker user'
  ansible.builtin.user:
    name: '{{ davrods_docker_user }}'
    groups: '{{ davrods_docker_user }},docker'
  become: true

- name: 'Get {{ davrods_docker_user }} home directory'
  ansible.builtin.shell: "set -o pipefail && getent passwd {{ davrods_docker_user }}  | awk -F: '{ print $6 }'"
  changed_when: false
  register: getent_output
  become: true

- name: Store davrods_user_home_path
  ansible.builtin.set_fact:
    davrods_user_home_path: "{{ getent_output.stdout }}"

- name: Create davrods docker directories inside {{ davrods_docker_folder }} folder
  ansible.builtin.file:
    path: '{{ davrods_user_home_path }}/{{ davrods_docker_folder }}/{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: templates/
  when: item.state == 'directory'
  become: true
  become_user: '{{ davrods_docker_user }}'
  notify: davrods_build_up

- name: Copy a certificates into davrods docker folder
  ansible.builtin.copy:
    src: '/etc/irods/{{ item.name }}'
    dest: '{{ davrods_user_home_path }}/{{ davrods_docker_folder }}/config'
    owner: '{{ davrods_docker_user }}'
    group: '{{ davrods_docker_user }}'
    mode: '{{ item.mode }}'
    remote_src: true
  with_items:
    - name: '{{ ir_ssl_certificate_key_file | basename }}'
      mode: '0600'
    - name: '{{ ir_ssl_certificate_chain_file | basename }}'
      mode: '0644'
    - name: '{{ ir_ssl_dh_params_file | basename }}'
      mode: '0644'
  become: true
  notify: davrods_build_up

- name: Deploy docker template files into davrods docker folder
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ davrods_user_home_path }}/{{ davrods_docker_folder }}/{{ item.path }}'
    mode: '{{ item.mode }}'
  with_filetree: templates/
  when: item.state == 'file'
  become: true
  become_user: '{{ davrods_docker_user }}'
  notify: davrods_build_up

- name: Make sure docker is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
  notify: davrods_build_up

- name: Prune unused davrods docker images
  ansible.builtin.command: 'docker image prune -af'
  changed_when: false
  register: prune_result
  failed_when: 'prune_result.rc > 1'
  become_user: '{{ davrods_docker_user }}'
  become: true

...
