---
- name: Install docker comunity edition.
  yum:
    name:
      - docker
      - python2-pip
    state: latest
    update_cache: yes
  become: true

- name: Install docker-py.
  pip:
    name: docker
  become: true
...
