---
- name: Install docker comunity edition.
  ansible.builtin.yum:
    name:
      - docker
      - python3-pip
      - docker-compose
    state: latest
    update_cache: true
  become: true

#- name: Upgrade pip to latest version
#  ansible.builtin.command: pip3 install -U pip
#  become: true
- name: Upgrade pip3 to latest version
  ansible.builtin.pip:
    name: pip
    state: latest
    executable: pip3
  become: true

- name: Install docker-py (supported by python 3)
  ansible.builtin.pip:
    name: docker
    executable: pip3
  become: true
...