---
- name: Install docker comunity edition.
  ansible.builtin.yum:
    name:
      - docker
      - python2-pip
      - docker-compose
    state: latest
    update_cache: true
  become: true

- name: Install docker-py.
  ansible.builtin.pip:
    name: docker
  become: true

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

...
