---
- name: Flush handlers.
  ansible.builtin.meta: flush_handlers

- name: Find all *.repo files in /etc/yum.repos.d/.
  ansible.builtin.find:
    paths: '/etc/yum.repos.d/'
    use_regex: false
    patterns: '*.repo'
    excludes: 'local_yum.repo'
  register: yum_existing_repos

- name: Remove *.repo files from /etc/yum.repos.d/ that do not correspond to our repos.
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ yum_existing_repos.files | map(attribute='path') | list }}"
  when: item | basename | regex_replace('.repo$','') not in yum_repos[os_distribution] | map(attribute='name') | list
  become: true

- name: Add custom yum repos.
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
  with_list: "{{ yum_repos[os_distribution] }}"
  become: true
...
