---
# Cloud image default user console password
cloud_console_pass: ''
# Pulp password and secret
pulp_api_password: ''
pulp_secret: ''
# LDAP credentials
#openldap_root_pw: ''
#openldap_root_hash: "Generate Argon2 password hash by using this command on the OpenLDAP server: /usr/local/openldap/sbin/slappasswd -o module-path='/usr/local/openldap/libexec/openldap' -o module-load='argon2' -h '{ARGON2}' -s '{{ openldap_root_pw }}'"
ldap_credentials:
  stack:
    readonly:
      dn: 'cn=readonly,dc={{ use stack_name here }},dc=local'
      pw: ''
      hash: "Generate Argon2 password hash by using this command on the OpenLDAP server: /usr/local/openldap/sbin/slappasswd -o module-path='/usr/local/openldap/libexec/openldap' -o module-load='argon2' -h '{ARGON2}' -s '{{ the pw for this user }}'"
    admin:
      dn: 'cn={{ use stack_prefix here }}-admin,dc={{ use stack_name here }},dc=local'
      pw: ''
      hash: "Generate Argon2 password hash by using this command on the OpenLDAP server: /usr/local/openldap/sbin/slappasswd -o module-path='/usr/local/openldap/libexec/openldap' -o module-load='argon2' -h '{ARGON2}' -s '{{ the pw for this user }}'"
# SRAM API token for PAM plugin.
#pam_weblogin_credentials:
#  api_token: ''
# Database user and password to be used by slurmdbd
slurm_storage_user: slurm
slurm_storage_pass: ''
# Root password for slurm MySQL/MariaDB database.
MYSQL_ROOT_PASSWORD: ''
# The password of the CA's ssh host signing private key.
ssh_host_signer_ca_private_key_pass: ''
# Mailing list config credentials.
#listserv_api_email_from: 'helpdesk address'
#listserv_api_email_to: 'helpdesk address'
#listserv_api_webinterface_url: 'listserv server'
#listserv_admin_user: 'admin'
#listserv_admin_pass: ''
#listserv_domain_name: 'domain'
# EGA Fuse Client.
#ega_fuse_client_credentials:
#  cineca:
#    user: ''
#    pass: ''
...
