---
- name: Deploy /etc/hosts file.
  ansible.builtin.template:
    src: templates/hosts.j2
    dest: /etc/hosts
    mode: '0644'
    owner: root
    group: root
    backup: true
  become: true
  tags: ['etc_hosts']
...
