---
- name: Create group folders in {{ mount_point }} with mode {{ mode }}.
  ansible.builtin.file:
    path: "/groups/{{ folder }}"
    owner: 'root'
    group: "{{ folder }}"
    mode: "{{ mode }}"
    state: 'directory'
  loop: "{{ folders }}"
  loop_control:
    loop_var: folder
  become: true
...
