---
- name: 'Compile list of volumes to mount for NFS servers.'
  ansible.builtin.set_fact:
    volumes: "{{ volumes | default([]) + [ volume ] }}"
  vars:
    volume:
      mount_point:  "/mnt/{{ item.pfs }}"
      device: "{{ item.device }}"
      mounted_owner: root
      mounted_group: root
      mounted_mode: '0755'
      mount_options: 'rw,relatime'
      type: ext4
  when: inventory_hostname in groups['nfs_server'] | default([])
  with_items: "{{ pfs_mounts | selectattr('type', 'search', 'nfs') | selectattr('device', 'defined') | list }}"

- name: 'Check the mount point.'
  command: "mountpoint {{ item.mount_point }}"
  register: mount_point_status
  failed_when: false
  changed_when: false
  loop: "{{ volumes }}"

- name: 'Create a filesystem on the device.'
  filesystem:
    fstype: "{{ item.item.type }}"
    dev: "{{ item.item.device }}"
  when: item.rc == 1
  become: true
  loop: "{{ mount_point_status.results }}"

- name: 'Mount the volume.'
  mount:
    path: "{{ item.mount_point }}"
    src: "{{ item.device }}"
    fstype: "{{ item.type }}"
    opts: "{{ item.mount_options }}"
    state: mounted
  become: true
  loop: "{{ volumes }}"

- name: 'Recheck the mount point.'
  command: "mountpoint {{ item.mount_point }}"
  register: mount_point_status
  failed_when: false
  changed_when: false
  loop: "{{ volumes }}"

- name: 'Configure permissions for mounted file system.'
  file:
    path: "{{ item.item.mount_point }}"
    state: directory
    owner: "{{ item.item.mounted_owner }}"
    group: "{{ item.item.mounted_group }}"
    mode: "{{ item.item.mounted_mode }}"
  when: item.rc == 0
  become: true
  loop: "{{ mount_point_status.results }}"

- name: 'Create group folders on volume.'
  include_tasks:
    file: create_group_folders.yml
  when:
    - item.mount_point == '/groups'
  loop: "{{ volumes }}"
...
