---
slurm_cluster_name: 'boxy'
stack_domain: 'hpc.rug.nl'
stack_name: "{{ slurm_cluster_name }}_cluster"  # stack_name must match the name of the folder that contains this vars.yml file.
stack_prefix: 'bx'
ldap_uri: ldap://172.23.40.249
ldap_base: ou=umcg,o=asds
ldap_binddn: cn=clusteradminumcg,o=asds
regular_groups:
  - 'umcg-atd'
  - 'umcg-lifelines'
regular_users:
  - user: 'umcg-lifelines-dm'
    groups: ['umcg-lifelines']
sudoers:
  - who: ['%umcg-lifelines-dms']
    become: 'umcg-lifelines-dm'
pfs_mounts:
  - pfs: umcgst08
    source: '172.23.34.213@tcp:172.23.34.214@tcp:'
    type: lustre
    rw_options: 'defaults'
    ro_options: 'defaults,ro'
lfs_mounts:
  - lfs: tmp03
    pfs: umcgst08
    groups:
      - name: umcg-atd
      - name: umcg-lifelines
...
