# If the sister role of 'rsyslog_client' will also be run on the, then it is
# higly suggested for this variables to be defined in the group variables
rsyslog_remote_path_key_dir: "/etc/pki/tls/private/"
rsyslog_remote_path_cert_dir: "/etc/pki/tls/certs/"
rsyslog_ca_key_file: "rsyslog-ca.key"
rsyslog_ca_cert_file: "rsyslog-ca.pem"
rsyslog_local_dir: "{{ playbook_dir }}/files/{{ stack_name }}/"
