---
ip_addresses:
  foyer:
    vt_internal_management:
      address: 10.10.1.122
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    external:
      address: 195.169.23.114
      netmask: /32
      fqdn: 'NXDOMAIN'
  vaxtron:
    DH4 Lustre:
      address: 172.23.58.84
      netmask: /32
    lustre:
      address: 172.23.12.49
      netmask: /32
    vt_internal_management:
      address: 10.10.1.123
      netmask: /32
  vt-dai:
    DH4 Lustre:
      address: 172.23.58.36
      netmask: /32
    lustre:
      address: 172.23.13.10
      netmask: /32
    vt_internal_management:
      address: 10.10.1.46
      netmask: /32
  vt-node-a01:
    DH4 Lustre:
      address: 172.23.58.65
      netmask: /32
    lustre:
      address: 172.23.14.156
      netmask: /32
    vt_internal_management:
      address: 10.10.1.182
      netmask: /32
  vt-node-a02:
    DH4 Lustre:
      address: 172.23.58.27
      netmask: /32
    lustre:
      address: 172.23.13.153
      netmask: /32
    vt_internal_management:
      address: 10.10.1.112
      netmask: /32
  vt-node-a03:
    DH4 Lustre:
      address: 172.23.58.68
      netmask: /32
    lustre:
      address: 172.23.14.20
      netmask: /32
    vt_internal_management:
      address: 10.10.1.226
      netmask: /32
  vt-repo:
    vt_internal_management:
      address: 10.10.1.71
      netmask: /32
  vt-sai:
    DH4 Lustre:
      address: 172.23.58.42
      netmask: /32
    lustre:
      address: 172.23.14.52
      netmask: /32
    vt_internal_management:
      address: 10.10.1.130
      netmask: /32
  vt_internal_management-external-router:
    vt_internal_management:
      address: 10.10.1.1
      netmask: /32
    external:
      address: 195.169.23.107
      netmask: /32
      fqdn: 'NXDOMAIN'
...
