---
ip_addresses:
  foyer:
    vt_internal_management:
      address: 10.10.1.122
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    external:
      address: 195.169.23.114
      netmask: /32
      fqdn: 'NXDOMAIN'
  vt_internal_management-external-router:
    vt_internal_management:
      address: 10.10.1.1
      netmask: /32
    external:
      address: 195.169.23.107
      netmask: /32
      fqdn: 'NXDOMAIN'
...
