---
- name: Copy blacklist-nouveau.conf file into modprobe.d to disable Nouveau drivers
  ansible.builtin.copy:
    src: blacklist-nouveau.conf
    dest: /etc/modprobe.d/blacklist-nouveau.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install NVidia persistence service
  ansible.builtin.copy:
    src: nvidia-persistenced.service
    dest: /etc/systemd/system/nvidia-persistenced.service
  become: true

- name: Enable a nvidia-persistenced service
  ansible.builtin.systemd:
    name: nvidia-persistenced.service
    state: started
    enabled: true
  become: true
...
