---
- name: Check if system needs to be restarted
  ansible.builtin.command: '/bin/needs-restarting -r'
  register: needs_restarting
  failed_when: 'needs_restarting.rc > 1'
  changed_when: 'needs_restarting.rc == 1'
  become: true
  notify: reboot_server

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Check if we have already configured NVidia devices
  ansible.builtin.command: 'nvidia-smi -L'
  register: smi
  changed_when: false
  failed_when: false
  become: true

- name: Install GPU driver if not all GPU devices are present and working
  ansible.builtin.include: gpu.yml
  when: ( gpu_count is defined ) and
        ( smi.stdout|default([])|lower|regex_findall('nvidia')|length != gpu_count )
...
